### ISSUE TITLE
Enable GPU slower than disable GPU

### ISSUE THREAD

**Issue by 233lol** [Yutaka-Sawada/MultiPar#10]
CPU: 3900x
GPU: RADEON VII
MUltipar 1.3.1.1
testfile size:49GB
Enable:6:53
Disable:6.19

**Comment by Yutaka-Sawada** [comment]
Using GPU isn't so fast sometimes. That is why the default setting is "disabled".

I wrote my OpenCL code on Intel's integrated GPU (Intel HD Graphics). After I got GeForce graphics board, I optimized it for NVIDIA GeForce GPU. Some AMD Radeon users reported that Radeon GPU was very slow with MultiPar. Though some users helped me to test sometimes, I could not improve perfomance on Radeon GPU. There may be a trick or special method to get full power of Radeon GPU, but I don't know yet. I cannot test myself, because I don't have Radeon GPU.

Thus, GPU acceleration may not work for Radeon GPU. I'm sorry for inconvenience. Please, un-check GPU acceleration on MultiPar setting.

**Comment by 233lol** [comment]
> Using GPU isn't so fast sometimes. That is why the default setting is "disabled".
> 
> I wrote my OpenCL code on Intel's integrated GPU (Intel HD Graphics). After I got GeForce graphics board, I optimized it for NVIDIA GeForce GPU. Some AMD Radeon users reported that Radeon GPU was very slow with MultiPar. Though some users helped me to test sometimes, I could not improve perfomance on Radeon GPU. There may be a trick or special method to get full power of Radeon GPU, but I don't know yet. I cannot test myself, because I don't have Radeon GPU.
> 
> Thus, GPU acceleration may not work for Radeon GPU. I'm sorry for inconvenience. Please, un-check GPU acceleration on MultiPar setting.
I test again in my laptop(i5 7300+gtx1050ti)whether enable or disable GPU,it used same time. It seems not to use GPU(630 or gtx 1050ti).

**Comment by Voczi** [comment]
> 
> 
> > Using GPU isn't so fast sometimes. That is why the default setting is "disabled".
> > I wrote my OpenCL code on Intel's integrated GPU (Intel HD Graphics). After I got GeForce graphics board, I optimized it for NVIDIA GeForce GPU. Some AMD Radeon users reported that Radeon GPU was very slow with MultiPar. Though some users helped me to test sometimes, I could not improve perfomance on Radeon GPU. There may be a trick or special method to get full power of Radeon GPU, but I don't know yet. I cannot test myself, because I don't have Radeon GPU.
> > Thus, GPU acceleration may not work for Radeon GPU. I'm sorry for inconvenience. Please, un-check GPU acceleration on MultiPar setting.
> 
> I test again in my laptop(i5 7300+gtx1050ti)whether enable or disable GPU,it used same time. It seems not to use GPU(630 or gtx 1050ti).

MultiPar uses my laptop's NVIDIA GPU just fine (GTX 1650 Max-Q). I wonder how much faster it actually gets with GPU acceleration on, but this project certainly beats par2cmdline by a mile..
