### ISSUE TITLE
Request: Media Size 5 formats

### ISSUE THREAD

**Issue by Nemesh64** [Yutaka-Sawada/MultiPar#102]
At this moment MultiPat has 4 media size I can select.
I have changed it for the media sizes I use:

4.37GB DVD:4690000000
7.9GB DVD:8480000000
25GB Blu-ray:23540000000
50GB Blu-ray:47760000000

But 4K/UHD is a new media type and I added that instead of DVD9.
I named it: 100GB UHD: 100000000000
It would be nice if there were 5 media size to choose from.
My preference would be:

4.37GB DVD:4690000000
7.9GB DVD:8480000000
25GB Blu-ray:23540000000
50GB Blu-ray:47760000000
100GB UHD: 100000000000

Can this extra field (so in total 5) be added to MultiPar?
With reghards,

Nemesh

**Comment by Yutaka-Sawada** [comment]
> Can this extra field (so in total 5) be added to MultiPar?

Yes, I can. But, I'm lazy to update all GUI resources. So, I changed initial settings only.

I add an option to add 5th item in "Media size" on Create window. Write this line `MediaList4=100GB UHD:100000000000` under `[Option]` section in `MultiPar.ini`. The item cannot be changed on GUI (MultiPar Options window). If many users want the 5th (or more) item in "Media size", I may consider to add the edit-box on MultiPar Options.

I put the sample (MultiPar_sample_2023-09-30.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4). Because I changed "lc" option in v1.3.3.0, you should update both MultiPar.exe and par2j64.exe at once. (If you don't use CPU settings, you don't need to update par2j.) Because 100 GB size is too large for me, I could not test the behavior on my PC. If it doesn't work correctly, please report the incident with example.

**Comment by Nemesh64** [comment]
Thanks Mr. Sawada-san.
At this moment I have a hollliday and hope to test it.
Would be really nice if there would be a 5th option in future versions.
With regards,

Nemesh
