### ISSUE TITLE
Version 1.3.3.0 being detected as a virus by Microsoft

### ISSUE THREAD

**Issue by SigmaTheDJ** [Yutaka-Sawada/MultiPar#105]
I just had this pop up on my PC: -

![Virus](https://github.com/Yutaka-Sawada/MultiPar/assets/65978073/cdfbdbaa-b6e6-48ca-aa2d-163cc1487016)

I downloaded the installer from GitHub, so I'm assuming it's a false positive. Just thought I would let you know.

**Comment by Yutaka-Sawada** [comment]
Thank you for reminding me how malware detection is obscure. If there is a problem in my source code or application, I will solve them as possible as I can. Because this is a mistake of others, I cannot do anything myself. So, no need to report this type incident. If you worry about malware, checking the file at [VirusTotal](https://www.virustotal.com) would be good.

You may see [VirusTotal result](https://www.virustotal.com/gui/file/b325e73f9fe42dcce6f4bd1b2e106a8da312c52b1cb8be7f332a70fc0cd4fe93/behavior). A sandbox "Yomi Hunter" flags the file as MALWARE. It points some basic features in MultiPar.exe like following. It runs another .EXE file. It creates short-cut icon. A user control it by command-line. It loads DLL. It starts batch file. It creates .INI file. It checks user's function key to show help. It gets data from clipboard for copy & paste files. As such functions are required for MultiPar's normal usage, I cannot stop them. "Yomi Hunter"'s reliability seems to be low, or it may not test actual behavior.

**Comment by SigmaTheDJ** [comment]
> Because this is a mistake of others, I cannot do anything myself.

As the developer of the software, you can report the false positive here: -

https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by Yutaka-Sawada** [comment]
> As the developer of the software, you can report the false positive here:

Yes, I did yesterday. Though Microsoft received my submission, it doesn't detect anything currently. It said that MultiPar.exe was a malware some hours ago. It says that MultiPar.exe isn't a malware now. I don't know what was happen in this hours. Microsoft might find its mistake and updated its database quickly.

Microsoft Analyst comments as below:
> We cannot reproduce any detection on the file. If the detection is still observed, follow the steps below to capture support log files from the system reporting detection.

[VirusTotal result](https://www.virustotal.com/gui/file/b325e73f9fe42dcce6f4bd1b2e106a8da312c52b1cb8be7f332a70fc0cd4fe93/detection) was changed. Though Microsoft is undetected, some others are false positive still. Do I need to report false positive to them, too ? But, I cannot find report page for "Yomi Hunter".
