### ISSUE TITLE
Par not executing

### ISSUE THREAD

**Issue by nf33** [Yutaka-Sawada/MultiPar#12]
See video.

https://youtu.be/5OIM8DzySD0

**Comment by Yutaka-Sawada** [comment]
Thank you for bug report. I thought that such bug was fixed in the latest version. I made a debug version to show process detail. I put the sample (par2j_sample_2020-10-04.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). The debug version is "par2j64_debug.exe" in the archive.

Please test it in your usage, save the log, and send it to me by e-mail. You can save log by checking an option "Log output of clients" in "Common options" section on "Client behavior" tab of MultiPar Option window. You can see the log saved folder by clicking "Open this user's save folder" in "Folder location" section on "System settings" tab. I will see what happened in the log, and try to fix the problem.

**Comment by Yutaka-Sawada** [comment]
Was this problem solved in the latest version 1.3.1.2 ? I'm not sure that the bug still exists or was fixed.
