### ISSUE TITLE
Can we get a slider for CPU utilization?

### ISSUE THREAD

**Issue by nf33** [Yutaka-Sawada/MultiPar#13]
Is it possible for you to add a feature that reduces the CPU utilization, and show the 'time increase' (how much time left) for using less cpu?

**Comment by Yutaka-Sawada** [comment]
There is no option to reduce CPU Utilization directly, because it's hard to predict. It's impossible to calculate 'time increase', too. 

When there are multiple cores in a CPU, MultiPar is possible to limit using cores. It's an item of "CPU usage" in "Hardware environment" section on "System settings" tab. You may set the slider to be lower, and see how is CPU utilization on your PC. 

If you want MultiPar to run at background mode, you may check "Run clients with lower priority" in "Common options" section on "Client behavior" tab.
