### ISSUE TITLE
2 suggestions to fix possible bugs

### ISSUE THREAD

**Issue by dgrainge** [Yutaka-Sawada/MultiPar#16]
1. when scanning files, multipar stops if there are damaged files and (at the same time) file names are not properly encoded, and Multipar wants to correct the file names. It will correct the names of undamaged files, but leaves damaged file names unaltered. The result is Multipar then cannot repair, because it believes some files are missing. If I manually rename the damaged files, Multipar can scan the complete file set and repair the files.
There must be a decision tree where Multipar chooses to rename files. I think it should choose to rename files, whether damaged or not, then look to see if repair is possible. I suspect it looks at a file's damage status first, and then doesn't look at renaming the file. It could be a matter of these two things being in the wrong order.

2. Under options I have chosed no repair automatically. I had a file with 13 recovery blocks, and 13 damaged blocks. I had to click to repair manually.  
It could be as simple as a line of code which should say if (# recovery blocks >= # damaged blocks) then do the repair. Maybe the code says > rather than >= ?

I have recently upgraded to 1.3.0.7 but I have seen problem 1 in earlier versions as well.

**Comment by Yutaka-Sawada** [comment]
> I think it should choose to rename files, whether damaged or not, then look to see if repair is possible.

It's difficult to implement. MultiPar can find misnamed files, only when they are not damaged. It uses Checksum (CRC-32) and Hash value (MD5) to search misnamed files. If a file is damaged, it's impossible to determine which one is the misnamed one of missing files. 

So, when you know filenames are encoded wrongly, you should correct them by yourself manually at first. You would be enough intellectual to recognize them, while MultiPar cannot.

Or, you may change setting to check all files under a base directory. You open "MultiPar Options", go to "Client behavior" tab, change "Verification level" to be "Additional verification" on "Verification and Repair options" section. This may be slow, but MultiPar will find more damaged blocks.


> It could be as simple as a line of code which should say if (# recovery blocks >= # damaged blocks) then do the repair. Maybe the code says > rather than >= ?

Auto-repair starts, only when full repair is possible. Because there is a fault in PAR2 specification, it may requires one more blocks than damaged blocks. But, it will be able to repair with equal number blocks mostly. (Failure rate seems to be very low.) Please click "Repair" button manually at that time.
