### ISSUE TITLE
[Request] Use of Descript.ion files to rename obfuscated downloads

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [Yutaka-Sawada/MultiPar#18]
Hi

Would it be possible for MultiPAR to examine the Descript.ion file with the aim of renaming obfuscated/unscrambled file names, I know it can rename misnamed files using the PAR2 file. I don't think this would be outside the main objective of MultiPAR. 

I use Newsleecher and NewsBIN Pro which both have the ability to download Descript.ion files

**Comment by Yutaka-Sawada** [comment]
> Would it be possible for MultiPAR to examine the Descript.ion file with the aim of renaming obfuscated/unscrambled file names

 This may be an interesting idea in a limited environment. Someone might request using MD5 / SFV ago as a similar idea. 

 It depends on what information the "Descript.ion file" contains. As far as I know from the Internet search, it will be difficult. Basically, it contains filename and some other meta data, such like description or date. To recognize a file as a misnamed file, it requires more information. 

 For example, there are misnamed 3 graphic files and "Descript.ion" for them;
1st_File.jpg, 2nd_File.jpg, 3rd_File.jpg, and Descript.ion.

 When the text data on "Descript.ion" is like below, can you rename them ?
~~~
Adam.jpg Picture of Adam
Bob.jpg Picture of Bob
Chaz.jpg Picture of Chaz
~~~

 It's impossible to distingush these files, unless you know who are they. Though human being is enough wise to understand the description sometimes, such feature would be very hard to implement on software. Therefore, you should rename such obfuscated/unscrambled filenames by yourself, because you are more intelligent than my handmade hobby product, hehe.

**Comment by Jamesstevens-3rd** [comment]
maybe this can help.
I searched for **Life in a Year 2020** and both programs download files named **TUc34Q7tjmBTmdz8l8**.part##.rar

**Newsbin Pro 6.28-5142** 
```
"TUc34Q7tjmBTmdz8l8.F628.par2" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
"TUc34Q7tjmBTmdz8l8.part01.rar" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
"TUc34Q7tjmBTmdz8l8.part02.rar" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
"TUc34Q7tjmBTmdz8l8.part03.rar" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
"TUc34Q7tjmBTmdz8l8.part04.rar" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
"TUc34Q7tjmBTmdz8l8.part05.rar" <Life.in.a.Year.2020.1080p.WEB.H264-NAISU\YOU.MUST.READ.THIS> TUc34Q7tjmBTmdz8l8 (02/89) - "TUc34Q7tjmBTmdz8l8.part01.rar" - 8,08 GB - yEnc, "grav45ghz87klu" <grav45ghz87klu@tzopwecmvnb.net>, alt.binaries.etc, Mon Nov 30 10:18:54 2020
```

**Nwesleecher 7 final**
```
"TUc34Q7tjmBTmdz8l8.part01.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part01.rar"
"TUc34Q7tjmBTmdz8l8.part79.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part79.rar"
"TUc34Q7tjmBTmdz8l8.part02.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part02.rar"
"TUc34Q7tjmBTmdz8l8.part03.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part03.rar"
"TUc34Q7tjmBTmdz8l8.part04.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part04.rar"
"TUc34Q7tjmBTmdz8l8.part05.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part05.rar"
"TUc34Q7tjmBTmdz8l8.part06.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part06.rar"
"TUc34Q7tjmBTmdz8l8.part07.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part07.rar"
"TUc34Q7tjmBTmdz8l8.part08.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part08.rar"
"TUc34Q7tjmBTmdz8l8.part09.rar" Life.in.a.Year.2020.1080p.WEB.H264-NAISU | unscrambled | TUc34Q7tjmBTmdz8l8 - "TUc34Q7tjmBTmdz8l8.part09.rar"
```

**Comment by Yutaka-Sawada** [comment]
The "Descript.ion" file includes a list of filenames. Newsbin and Nwesleecher may compare the description and will download files on the list. Their feature is nice to search files by its contents.

I'm not sure how to use it to rename misnamed files. When a filename is different from that on list, it's impossible to recognize which one. "Descript.ion" file is useful to pick-up a group of files by their correct filenames from many scrambled files. Even when the filenames are obfuscated/unscrambled, the names are listed as they are. (Original filename isn't written.)

**Comment by Jamesstevens-3rd** [comment]
I think you have it wrong way round, Newsleecher and Newsbin both create an empty text file Descript.ion and as each file is downloaded the program will write an entry in the Descript.ion file, each file will have its scrambled name followed by its unscrambled name on a **single line**.
It doesn't matter if each scrambled file name is different because its unscrambled name is on the **same line** in the Descript.ion file, these two programs always write scrambled/unscrambled file names on a single line 

you can parse a text file to locate words, in this case you have the file on the hard drive you want to rename you parse the Descript.ion text file for that scrambled name **and on that line** of text will be the unscrambled file name.
Google this text _programming: how to read file names from a text file_

I don't know what language you have written MultiPAR ?, C++, visual C, Basic ?  but it ant be that difficult as we did parsing a text file in school in 1980's... yes I'm that old ;o)

Newsleecher is now free to use as a download tool, Supersearch and Superleech are subscription based.
http://www.newsleecher.com/forum/viewtopic.php?p=118875#p118875

**Comment by Jamesstevens-3rd** [comment]
I think you have it wrong way round, Newsleecher and Newsbin both create an empty text file Descript.ion and as each file is downloaded the program will write an entry in the Descript.ion file, each file will have its scrambled name followed by its unscrambled name on a single line.
It doesn't matter if each scrambled file name is different because its unscrambled name is on the same line in the Descript.ion file, these two programs always write scrambled/unscrambled file names on a single line

you can parse a text file to locate words, in this case you have the file on the hard drive you want to rename you parse the Descript.ion text file for that scrambled name and on that line of text will be the unscrambled file name.
Google this text programming: how to read file names from a text file

I don't know what language you have written MultiPAR ?, C++, visual C, Basic ? but it can not be that difficult as we did parsing a text file in school in 1980's... yes I'm that old ;o)

Newsleecher is now free to use as a download tool, Supersearch and Superleech are subscription based.
http://www.newsleecher.com/forum/viewtopic.php?p=118875#p118875

**Comment by Jamesstevens-3rd** [comment]
I think you have it wrong way round, Newsleecher and Newsbin both create an empty text file Descript.ion and as each file is downloaded the program will write an entry in the Descript.ion file, each file will have its scrambled name followed by its unscrambled name on a **single line**.
It doesn't matter if each scrambled file name is different because its unscrambled name is on the **same line** in the Descript.ion file, these two programs always write scrambled/unscrambled file names on a single line

you can parse a text file to locate words, in this case you have the file on the hard drive you want to rename you parse the Descript.ion text file for that scrambled name and on that line of text will be the unscrambled file name.
Google this text _programming: how to read file names from a text file_

I don't know what language you have written MultiPAR ?, C++, visual C, Basic ? but it can not be that difficult as we did parsing a text file in school in 1980's... yes I'm that old ;o)

Newsleecher is now free to use as a download tool, Supersearch and Superleech are subscription based.
http://www.newsleecher.com/forum/viewtopic.php?p=118875#p118875

**Comment by Yutaka-Sawada** [comment]
Oh, I see. I understand what you want. Newsleecher and Newsbin create a "Descript.ion" file, which includes list of many sets of scrambled name and unscrambled name. 
In the example,
"TUc34Q7tjmBTmdz8l8.*" is scrambled name.
"Life.in.a.Year.2020.1080p.WEB.H264-NAISU" may be unscrambled name.

Then, you want to change (rename) the "TUc34Q7tjmBTmdz8l8" to be "Life.in.a.Year.2020.1080p.WEB.H264-NAISU" by reading the "Descript.ion" file. When the format is static, it's possible to rename those sets. You can do the task with most renaming tools by reading the "Descript.ion" file yourself and type the set manually. 
Such like; 
From : "TUc34Q7tjmBTmdz8l8"
To : "Life.in.a.Year.2020.1080p.WEB.H264-NAISU"

But, this is out of MultiPar usage. It's a independent renaming tool. It may be simple only to supports "Descript.ion" file format of Newsleecher or Newsbin. Technically, I (and most programers) can make such software, if there are enough sample sets of "Descript.ion" files and scrambled/unscrambled list. Making a single task application is easier than multi feature utility. However I don't know the usage is useful. (It's very limited case.)

As a practice of C language, I made a simple console application. I put the sample (IonName_2020-12-05.zip) in "Tool" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Because it's not MultiPar's subject, I put it in another folder. I made it for TDM-GCC and source code is included. You may test or modify the application for your usage.
