### ISSUE TITLE
[Feature] hide output in the command line for healthy files

### ISSUE THREAD

**Issue by RueleuR** [Yutaka-Sawada/MultiPar#23]
Thanks for your program. It would be nice to have a parameter for verification that skips all the logging output if everything is OK. It should only print errors, missing or renamed files including the path. I know a similiar option from https://github.com/rhash/RHash . There it is called "--skip-ok" _Don’t print OK messages for successfully verified files._

Background: 
I'm using multipar to add additional recovery options to backups. I create and check multiple separate par2 files for separate (sub)folders. So at the end I've a lot of files like .\2000\2000.par2 , .\2001\2001.par2, .\200X\200X.par2, ... that are OK normally. The verification of all the files creates a very long logging output. There it is hard to see if everything is OK with just a quick look. It would be much easier if only the errors are visible.

Just for information which command lines are used:
Create one par2 file:
`"E:\MultiPar\par2j64.exe" c /ss262144 /sn32768 /sm4096 /rr1 /rf1 /lc32 /m0 /in "E:\Files\2000\2000" *.*"`
Create multiple par2 files which belong to different files in different subfolders with "FORFILES":
`FORFILES /P "." /M "*" /c "cmd /c echo @path/@file" ` (example for FORFILES)
`FORFILES /P "." /M "*" /c "cmd /c \"\"E:\MultiPar\par2j64.exe\" c /ss262144 /sn32768 /sm4096 /rr1 /rf1 /lc32 /m0 /in @path/@file *.*\""`

Check routine for one file:
`"E:\MultiPar\par2j64.exe" v /vl2 /m0 "E:\Files\2000\2000.par2"`
Check routine for mulitple par-files which belong to different files in different subfolders. It checks independently all par2-files in subfolders that are found by FORFILES. FINDSTR tries to reduce the logging output.:
`FORFILES /P "." /S /M "*.vol*.par2" /c "cmd /c \"\"E:\MultiPar\par2j64.exe\" v /vl2 /m0 @path\"" | findstr /C:"Missing  :" /C:"Misnamed :" /C:"Damaged  :" /C:"All Files Complete" /C:"Recovery File" /C:"File Description packet is missing" /C:"PAR File(s) Incomplete" `

**Comment by Yutaka-Sawada** [comment]
> It would be nice to have a parameter for verification that skips all the logging output if everything is OK.

I don't want to make such option, because it's possible to distinguish by Exit Code. I didn't know a command like FORFILES nor FINDSTR. It seems to be useful. I tested the behavior and it can call Batch Script. So, you can do more complex task for each PAR2 file.

For example, I made a batch script file "save_log.cmd". Then, FORFILES can call the batch file like below;

```
FORFILES /M "*.vol*.par2" /c "cmd /Q /C \"\"E:\Test\save_log.cmd\" @path\""
```

Then, the batch file accepts PAR2 file's path. It calls par2j64.exe to verify the PAR2 file, and saves the output log on a temporary file. After verification, it checks the Exit Code by ERRORLEVEL. If PAR2 files and source files are complete, ERRORLEVEL becomes 0. When ERRORLEVEL is 0, it just delete the temporary file. When ERRORLEVEL is over than 1, it will append the temporary log after a main log file. You may read the main log file to see what error happened later. I post the sample batch file here. You may modify the script for your usage.

```
@ECHO OFF
SETLOCAL

SET par2_path="E:\MultiPar\par2j64.exe"
SET log_path="E:\Test\error_log.txt"

REM Verify and save log. Use ">>" to append. Use ">" to over-write.
%par2_path% v "%1" > "%~n1.temp.txt"

IF ERRORLEVEL 1 (
REM Process following code, when something error occurs.

ECHO Error %errorlevel% at %1

IF EXIST %log_path% (
COPY /A %log_path% + "%~n1.temp.txt" %log_path%
DEL "%~n1.temp.txt"
) ELSE (
MOVE "%~n1.temp.txt" %log_path%
)

) ELSE (
REM Process following code, when there is no error.

DEL "%~n1.temp.txt"

)

:End
ENDLOCAL
```
