### ISSUE TITLE
MultiPar GUI layout will be changed a little

### ISSUE THREAD

**Issue by Yutaka-Sawada** [Yutaka-Sawada/MultiPar#24]
I plan to increase the max of slice size in my PAR2 clients. Though I thought that 1 GB was enough for PAR2, [some ParPar users seem to set larger slice size](https://github.com/animetosho/ParPar/issues/26). Because I use 32-bit integer for working buffer area, 1.3 GB is the theoretical limit in my code. That is 4 GB / 3 = 1.3 GB. If I omit searching blocks from damaged files, it will be possible to support upto 4 GB slice size. There is a limit of 4 GB for file IO in Win32API. To support over than 4GB slice size, I need to modify my code largely. 

At this time, I changed my par2j to support upto 1.3 GB at next version. (I just change the limit value from 1 GB to 1.3 GB, hehe.) As this doesn't cause over-flow, there will be no problem. Max of split size was increased from 2 GB to 4 GB, also. (This was the max of 32-bit integer.) Because I don't use the file splitting feature by myself, I didn't test so much. It may work, if nobody claims a problem.

Now, I found a problem in modifying MultiPar GUI. Windows common control's edit-box supports max 2 GB value. (It's signed 32-bit integer.) Furthermore, current edit-box is narrow. I increased width of 2 edit-boxes (split size and slice size) for test. I aligned other boxes, too. Then, width of edit-boxes becomes different. (They are same on QuickPar.) I feel that this layout would be acceptable on Windows 7. If someone has a problem or trouble in using other OSes, please report the incident. 

I put the sample (gui_layout_2021-02-13.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by Yutaka-Sawada** [comment]
I updated each language UI DLL. They have a bit wider edit-box for block size and split size. It may be possible to support up to 1.3 GB block size with the GUI. But, I didn't test the creation nor verification yet. 

I came up with a new idea to support 2 GB block size with small change in my code. I will try more. 

I put the current sample (gui_layout_2021-02-18.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by Yutaka-Sawada** [comment]
I changed max block size of par2j to be 2 GB. It's 2020 MB on MultiPar GUI. Normally users should not set so large block size. (100,000,000 bytes = 95 MB seems to be the max possible block size on QuickPar.) For par2j 32-bit version, 500~600 MB block size may be the limit for detailed verification. Even with par2j 64-bit version, block size * 3 times memory area is required for fast file access. Mostly, block size * 2 times memory area is required for detailed verification. If there is no enough memory area, it will use simple verification automatically.

I tested 480 MB block size with 32-bit version. Though it worked well on 64-bit OS, it may not work with the limited RAM on 32-bit OS. I tested 1.6 GB block size, and it worked slowly with 64-bit version. 32-bit version cannot detect enough blocks on a damaged file. The test was very slow on my HDD, and it looked like as if freeze. Unless you have a strong reason to set so large block size, you should not try such extreme size. This change is only for a rare case.

I put the current sample (gui_layout_2021-02-22.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by pmatuszy** [comment]
@Yutaka-Sawada - if you need somebody to do some tests I have 2 machines with large RAM (128GB and 64GB). Let me know if you need some help with testing.
Paul

**Comment by Yutaka-Sawada** [comment]
Thanks Paul for the kind offer. If you have a file of 6 GB over size, please test 2 GB (2020 MB) block size. 

1) Set 6 GB over source data for 2 GB block size. There are more than 3 source blocks.
2) Create PAR2 file with 2 recovery blocks for them.
3) With binary editor, delete some bytes in front and at the last of the source file.
4) Then, two (first and last) source blocks are damaged now.
5) Verify the broken file.
6) If it finds complete source blocks in the damaged file, sliding search works well.
7) Try to repair the file with 2 recovery blocks.
8) If it recovered lost blocks and repaired the file, it's OK.
9) I will be able to write that 2020 MB block size was tested to work well. =)

Though I should have solved all over-flow problem, I might miss something. When it fails, I need to review my code again. At this time, there is no requirement to support larger block size than 2 GB. In most cases, setting many small blocks is better than a few big blocks for redundancy.

**Comment by pmatuszy** [comment]
Hi

no problem. The instruction is not clear to me to be honest. we can talk it
over (my watsapp / signal telephone number  is in the signature).

Do I need to generate test data myself or you provide test scenarios and
data?

I think it would be easier to talk it over ...

Regards

Paul G. Matuszyk
+41.76.369.1467

All the views expressed in this email are mine, and do not necessarily
represent those of my client (or possibly anyone else in the known
universe). No animals were harmed in the creation of this message. May
contain nuts. In order to preserve the world's resources, this email was
composed from refurbished pixels recycled from previously-used emails.
Ingredients: E-113, E-120, E-9999, EI-EI-O. If you have read this far -
don't you have anything better to do with your time?

**Comment by Yutaka-Sawada** [comment]
> Do I need to generate test data myself or you provide test scenarios and data?

I don't know that you have a big file. I cannot send big data over the internet. I won't understand your English complex speaking words, as I use a dictionary and online translator to write this English text, hehe. I'm sorry for my poor English language skill.

When you don't have a big file, you need to generate the testing file with irregular bytes. For example, if all bytes in the file is same or has continuous pattern, it's impossible to determine source blocks. Those regular byte pattern is bad to test verification. 

What kind of file or how to brake file is not so important. Anyway, MultiPar needs to work on each user's case. The file should be enough large to contain 3 source blocks. After you create PAR2 file (2 recovery blocks) for the source file, you damage the first source block and the last source block in the file. Verification should find a complete source block between these damaged source blocks. 

MultiPar (par2j) has 2 kinds of verification methods; simple verification (linear step offset) and detailed verification (sliding byte offset). I wanted to know the detailed verification works for 2 GB block size. 

If your using binary editor doesn't support GB order size, you may simulate damage by joining some files. I did so on my PC. For example, there are 3 files; A, B, C. (A and C must be smaller than B in this usage.) Join them to construct a big file ABC. Use the file ABC as a source file. Use the file B as a damaged source file.

**Comment by JohnLGalt** [comment]
Hi,

Since I have a large amount of RAM in my system as well, I'll test also.  

1. I created a .7z archive of several Iron Maiden albums, total size of archive is 6,527,535,996 (6.07 GB).
2. I copied file to older SATA III SSD and newer NVMe SSD (dual testing based upon drive speed :D )
3. I downloaded the HEX editor from https://github.com/philipxyc/SuperHexEditor (through Windows Store) as it was easy and fast to load 6 GB file (I suspect it loads only small chunks of data at any given time, making it easier to handle really large files).
4. I downloaded 2-22 archive from 'Samples' folder, extracted, then copied my 'MultiPar.ini' and 'MultiParShlExt.ini' (just for reference - I can run tests with fresh extraction of files without .ini files if need be).
5. I run MP test 2-22.  Add file from SSD.  Change 'Number of Recovery Blocks' and 'Number of Recovery files" both values to '2', then clicked 'Create' button.
6. After creation of .par and 2 volx+1.par2 files, I clicked 'Verify' button and verified all was well.
7. I opened HEX editor and changed first HEX value from 07 to 00 and last HEX value from 00 to FF.
8. I opened main .par2 file in MP Test build - verified that archive was, in fact, damaged, and that it was ready to be fixed using existing 2 recovery files.
9. Repaired archive, MP test build states complete.  Opened archive with 7-Zip, and tested archive, test passed.  Verified hashes of modified and repaired archive with second, unedited copy of archive SxS - same hashes (CRC32, MD5 and SHA1) as well.

So, it worked for me.

**Comment by Yutaka-Sawada** [comment]
> So, it worked for me.

Thanks John L. Galt for test. When there are enough RAM to keep source files and working buffers, verification might be acceptable speed. Though I don't recommend to set such large block size in normal usage, it's good to work for some special or rare cases.

**Comment by JohnLGalt** [comment]
That makes sense.  Since I have 128 GB RAM, I don't see any time that it may cause problems for me.  But switchable large size or not would be good as an option.

Is there a minimum that should be installed, say, maybe like 32 GB or more?  And if you make it user-enable feature, will the programming check for a minimum amount of RAM installed before allowing user to enable?

**Comment by Yutaka-Sawada** [comment]
Verification will requires at least "block size * 2" size buffer for detailed verification method. So, 4 GB free RAM space is the minimum requirement for 2 GB block size. It may become as faster as having more free RAM space for disk cache. 

Even when there is no enough RAM, it still can verify and repair. But, it may fail to find complete blocks in damaged files. Then, the repair may become slower and less possible. At this time, I don't make an option to limit block size.

**Comment by JohnLGalt** [comment]
So, theoretically, I could have it run at 64 GB block size lol.

Yeah, no - I think 2 GB is fine.
