### ISSUE TITLE
1.3.1.4 seems incompatible with other versions

### ISSUE THREAD

**Issue by nutpantz** [Yutaka-Sawada/MultiPar#27]
Just updated and when i went to check a file created with par2j 1.3.1 is marked every 338 files damaged (completely unusable) and 1 file good.
And older version (1.3.0.6) marks 339 files good  and every par for 8 good blocks

I've tried with 4 or 5 different versions ai swear I'm getting s slighty different result with each version
If verification  method is changing it needs to auto match with old versions.

Update just created new pars for 5gb of 20mb files and on verification every child and par was damaged but one.
So 1314 is broken using Windows 10

**Comment by Yutaka-Sawada** [comment]
> I've tried with 4 or 5 different versions ai swear I'm getting s slighty different result with each version

Thank you for bug report. It's a strange behavior, which I never saw yet. I didn't change verification method. Though I changed MD5 function at v1.3.1.4, previous versions were same. So, there should be another reason in their different results. 

At first, created PAR2 files should be perfect. Do you have another PAR2 client, such like QuickPar or par2cmdline ? You should use it to check PAR2 files are complete or not. When v1.3.0.6 reports them as good status, they might be complete. 

Because damage status is varied by versions, source files should be complete. You may check them with another PAR2 client, too. As the damaged status is completely unusable, something file IO error might happen. Access violation caused missing status. It could access the source file, but could not read data at all. Then, the file might be marked as damaged status with 0 block found. I don't know why it could read data from source file.

Log files are helpful to see the difference. You check "Log output of clients" in "Common options" section, on "Client behavior" tab, on MultiPar Options window. The log file is a text format "MultiPar.log" in save folder. You may open the save folder by double-clicking text area under progress-bar on Verify window. Or you may click "Open this user's save folder" button in "Folder location" section, on "System settings" tab, on MultiPar Options window. Please post the log files here or send them to me by e-mail.

**Comment by nutpantz** [comment]
what is your public email address?
i would rather not post the log here with the filenames

**Comment by nutpantz** [comment]
i think the error 
"input file slice checkcum packet is missing"

is likely the issue

**Comment by Yutaka-Sawada** [comment]
> what is your public email address?

My e-mail address is written on "ReadMe_English.txt". That is "tenfon(at mark)outlook.jp". 

> multipar 1.29 seems to work 100% so far 1.3.1.4 fails 99% on every file.

If the miss recognized file is random, there may be a hardware error. If MD5 checksum calculation was failed, all files should be bad. It's odd that old version works well. Is there a effect of Anti-virus software or something another application ? When there is a hardware problem or another software avoids accessing files, MultiPar cannot run properly.

> "input file slice checkcum packet is missing"

This means that it could not find the packet in PAR2 files. So, it failed to check PAR2 files as same as source files. The problem might be serious. Does other application treat the drive correctly ? You may check SMART info of the drive.

**Comment by nutpantz** [comment]
multipar 1.3.1.3 works prefect on the files where 1.3.1.4 fails..
i created log file  for both 1313 and 1314 for both creating parfiles and verifying them done right after each other.
( they are both emailed to you already)
i have no active antivirus ( my windows pc is for offline gaming) my last virus scan was on the last weekend and is clean with nothing installed since.
everything else i have has never reported an error like this.

**Comment by nutpantz** [comment]
update.
it might have to do with long filenames, most of my filenames are longer.
but i just hit a short filename one and everything was fine for verifying it

**Comment by Yutaka-Sawada** [comment]
I found a bug in my hash calculation code for SSD. When a file size is multiple of block size, MD5 hash of "Input File Slice Checksum packet" had been wrong. There was a bad addressing in treating the last block. (The error happened, when there was no padding bytes.) I fixed the bug and made a sample to test. Please test it. To test the sample, you don't need a line of "FileAccess=1". 

Anyway, when your source files' size were multiple of block size, the created PAR2 files by v1.3.1.4 were bad. Because this bug was serious, I will release the next v1.3.1.5 as soon as possible. I need to refine verification code a little. When you confirm the result, please post. You need to re-create all PAR2 files, which you used v1.3.1.4. I'm sorry for this problem, and thank you for the report. If you didn't report the bug, I and most users might not see. 

I put the sample (gui_sample_2021-03-04.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by nutpantz** [comment]
My system and games drive are ssd my other two drives are standard and I have 6 USB non ssd hard drives.
