### ISSUE TITLE
Downloads through Git 'releases' section?

### ISSUE THREAD

**Issue by JohnLGalt** [Yutaka-Sawada/MultiPar#28]
Hi,

Just curious if it is possible to use Releases feature of GitHub for posting releases - it would allow users following the project (all 6 of us) to get notifications when new build is released instead of having to check manually.

**Comment by Yutaka-Sawada** [comment]
I didn't know the usage. I referred par2cmdline's page. The release feature seems to be useful. It keeps every old version. A user may download his favorite version and read release note. 

I tested the feature for v1.3.1.5. I did copy and paste the latest release note. Upload binary files. (.ZIP and .EXE package) It looks good. 

But, the source code item seems to include all files on my main page. I might use GitHub page wrongly. Should I remove binary files from the default page ? I treated "README.md" as release note ago. Should this be an introduction page of MultiPar ? Then, I may put source packages only. Do most GitHub users know release item on right panel ? 

Because I didn't know the release usage, I wonder where I can download compiled binary files from other one's GitHub page for long. Thank you for teaching the release feature usage.

**Comment by JohnLGalt** [comment]
Most repositories I have seen use it, but not all.  The release section is
where binaries, past and present, usually are available, along with preview
/ ßeta  builds.

By using release you can remove binaries from main page.

Also, most repositories I have seen use main page as viewing of README.md,
but some instead use it as more in depth information page for project,
separate from README.md.

I can link several other repositories I watch as examples, although another
developer like animetoshi might be better help to you as they actually
develop files on GitHub and have a better understanding of the resources
available for you to use.

**Comment by JohnLGalt** [comment]
Here is a plugin for KeePass application:

https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader

Here is the main repository for Android root method Magisk:

https://github.com/topjohnwu/Magisk

Both use a very extensive README.md as source for main page information.

Here is MusicBrainz utility Picard page:

https://github.com/metabrainz/picard

As you can see it is a very basic README.md.  But if you look at their release section, not only do they link directly to patches added to codebase, but they also include directly downloadable SHA256SUM file for each release that can be downloaded by users.

Here is GrepWin, in both x86 and X64 MSI and portable .ZIP:

https://github.com/stefankueng/grepWin

Here is abbodi's VC Redistributable All in One installer:

https://github.com/abbodi1406/vcredist

In releases section he posts both checksums of the .ZIP that users download *and* the checksums of the AIO installer inside the .ZIP file.

Since we're at GitHub, it would not be fair to not include a Microsoft utility, so here is Microsoft PowerToys for Windows 10:

https://github.com/microsoft/PowerToys

See the extensive README.md page?  Links to other utilities, including dependencies to instally PowerToys, Roadmap, explanation of preview builds and features, and much, much more.  Even on release page ther eis a lot of information also, not just the files and checksums.

Another Microsoft utility, the FOSS Powershell for cross-platform usage.

https://github.com/microsoft/PowerToys

You get the idea.  So many different ways to do it - you pick what you want to do with it and use it that way.

And yes, the main reason I asked about the use of release section was *specifically* so users could *easily* revert to a previous version if current version caused issues, because all previous versions you put there will always be available.

**Comment by JohnLGalt** [comment]
Looking good!  I'll close this now ;)
