### ISSUE TITLE
MultiPar helped me from silent data corruption

### ISSUE THREAD

**Issue by Yutaka-Sawada** [Yutaka-Sawada/MultiPar#31]
I could install Visual Studio 2019 and tried to resume MultiPar development slowly. But, as I found a strange problem, most files which I copied from backup HDD were broken. When I tested current MultiPar behavior on Windows 10 by using sample set of PAR2 files, both sample source files and PAR2 files were damaged. I thought that it was something wrong with a hardware.They are not small bit error, nor several bytes, but some KB area is changed in some position. 

Then, I check other files with MultiPar. (I made PAR2 set for MP3 files ago.) The corruption frequency was high. I needed to re-copy from backup HDD again. Original files on backup drive are OK, but copied files were damaged. I'm not sure the cause of this problem. I checked new PC's RAM and SMART info of SSD. Because downloaded files seem to be OK (Windows Update and Visual Studio's download installer worked.), the error happened on files from external HDD only at this time. I felt that this might be a problem of USB device. 

When I replace broken files with complete files from backup drive again, error did not happen. New copied files are all OK this time. (I checked them with MultiPar. ) I don't know what happened at the first time. I don't know the problem was solved somehow or there is unknown corruption still. At least, I understand that backup is important, and also backup isn't enough. Backuped data may be damaged while transfering between devices. Checksum (or MultiPar) is useful to check their integrity.

**Comment by pmatuszy** [comment]
Hi - Use Total Commander for copy and verify (https://www.ghisler.com/). It copies data and crosscheck source and destination with the checksum.
The same feature has TeraCopy (https://www.codesector.com/teracopy).

If you suspect RAM error use Memtest from .ORG site https://www.memtest.org/ not memtest.com
Regards
Paul

**Comment by JohnLGalt** [comment]
Also, with mechanical HDs, Windows tends to auto schedule defragmentation, and it is *supposed* to run in background when computer is not being used - but it has led to errors before because it is silently running while file is being accessed / used.  Since you are using SSD, defrag should not be playing a role, but *do* verify that your OS is set to automatically use Trim on SSD on a regular basis.

But another cause of such strangeness is also malware, as I learned a few decades ago - I was infected with a particularly virulent (for that time) worm that infected each and every self-extracting .ZIP file I had created.  The underlying archives were not affected, but the execution of the self-extraction modules (using PKZip back then) failed on every single .ZIP that I had converted to sefl-extracting.  Luckily, as I said, it did not alter the actual archives themselves and I was able to (manually) extract every file and make new archives of them.  

One more thing - did you try using older versions of MultiPar to see if error was specific to later versions?

**Comment by Yutaka-Sawada** [comment]
Thanks Paul G. Matuszyk and John L. Galt for advice. 

After I found the data corruption, I started to use FastCopy (https://fastcopy.jp/) to copy & verify files from external HDD, but such error didn't occur at next time. When I used Windows 10 's memory test feature to check RAM, it reported no error.

I thought that OS doesn't defrag SSD. I disabled the auto schedule defragmentation on the SSD now. Because Anti-Virus software (Norton Security) was pre-installed on new PC, it was not caused by a malware. Also, I used another hash (SHA-1) checker to detect damaged files. So, it was not a failure of MultiPar.

**Comment by JohnLGalt** [comment]
Also verify that Windows is set to Trim SSD.

**Comment by Yutaka-Sawada** [comment]
I see. I checked the TRIM item. It's enabled. (Windows OS seems to set automatically for SSD.)

**Comment by JohnLGalt** [comment]
Yeah, it is *supposed* to - but sometimes it has failed to set on an SSD, particularly Win 7.  So wanted to be sure ;)

**Comment by Yutaka-Sawada** [comment]
After one week, there is no problem of copying files at this time. It should not have been a hardware error, because it works well now. When I copied all files from an old backup HDD (13 years old !) to a newly bought HDD, there was no problem at all. 

Though there is no evidence, there might be a problem in USB driver. I came up with this probability by checking history of Windows Update. There was an item of "Intel - SoftwareComponent" in driver update. When a neighbor complained PC problem, I saw some odd behavior on Windows 10 with driver update and fast startup. From searching the Internet, "fast startup" feature seems to be bad. Almost of all web-sites suggest to disable "fast startup". Because Windows Update changed the driver sliently and I didn't disable "fast startup", incomplete driver might fail to control the USB device. After I disabled "fast startup", driver becomes complete and works correctly. 

When I search the Internet, sometimes "USB selective suspend" is mentioned to cause error on a USB device. I don't know this was my case or not. Because the USB HDD was recognized from PC, its power resumed. This suspect's probability may be lower than "fast startup".

**Comment by JohnLGalt** [comment]
Yeah, a lot of times Fast Startup, particularly on older hardware, tends to get in the way rather than actually functioning correctly.  The new machine I built last year seems to have no  issues with FS, thankfully.

As for USB selective suspend - I turn off all selective suspend settings for HDs, NICs, and USB on all my installs.  So my machine only reboots when I want it to, and sleeps only when I want it to - otherwise all hardware is always available.  If I need the machine off, I power it off - I don't let the OS / hardware determine anything like that (exception is CPU states, which I do let the OS / hardware maintain, so CPU is not always running at 100% power unless needed).  I find my machine tends to be more responsive with those disabled, as I need, without having to wait for items to becomes available.  

It mgiht even be something as superficial as a TRIM operation was actively being used when the data was copied.  (This should not be applicable, but Windows does some really stupid things sometimes).  Who knows?

At least it is better now.

You should also verify what type of RAM you have installed, and how many sticks, because if it is 2x 4 GB sticks, you'll need 2x 8 GB sticks, but if it is 1x 8 GB stick, then getting a matching stick is doable (although still better to buy a matched set to prevent little, usually minor, inconsistencies).
