### ISSUE TITLE
Source files don't match version number of binary releases

### ISSUE THREAD

**Issue by mcheah** [Yutaka-Sawada/MultiPar#39]
I downloaded 1.3.0.7 as a release since it's the last non-beta and thought I'd poke around the source code to verify the functionality, however, the readme.md states the version is 1.3.1.5, and the included source files seem to point to newer versions.  For transparency, it would be nice to be compile the last supported non-beta from source, but I suspect that things just got jumbled up from the transition to github.

I'll poke around the Onedrive to see if the archives there match up better.  It might make sense to provide a singular release for the files hosted on Onedrive here, or making a tagged archive commit so that others can find everything in one place.  Onedrive/dropbox links tend to go stale over time as projects move on, so it'd be nice to keep everything in github.

**Comment by Yutaka-Sawada** [comment]
I'm sorry for the old version package's mismatch. GitHub includes source code of the releasing time. Because I didn't use GitHub's release feature at the time of v1.3.0.7, I put it later. 

As you find, there are many old versions' source code package on OneDrive. Please refer OneDrive for old versions. I use OneDrive for backup. I use GitHub for web-forum (issues page) mostly. I'm not good at using GitHub feature yet. There will be no problem at downloading files on GitHub for newer versions.
