### ISSUE TITLE
[Feature Request] Full scanning of Data Files residing on the Bad Sectors during Verification

### ISSUE THREAD

**Issue by swarup459** [Yutaka-Sawada/MultiPar#45]
Magnetic HDDs develop Bad Sectors gradually over time. If any file by any means resides on those bad sectors, technically it is corrupted. We can repair that corrupted file using the PAR2 recovery files.

I did a test where I created 10% PAR2 recovery from a fresh copy of a file. Then, I created some copies of that file to one of my older HDDs where bad sectors were present. Luckily, two copies fell on those bad sectors. When I verified them against the previously created PAR2 recovery file, **the par2j client(v1.3.1.9) couldn't scan the whole file**. It stopped where it found the first bad sector and gave a Read Error (**0x17, Data error (cyclic redundancy check)**). As a result, it needed more slices than the actual requirement to repair the whole file.

Now, when I recovered those partially corrupted files to a good HDD using [DDRescue-GUI](https://launchpad.net/ddrescue-gui), it appeared that both the files lost only one slice each due to the bad sectors and they were totally repairable.

So, **if the bad sector is encountered at the beginning portion of the file, the file will be irrepairable using 10-20% recovery even though there is sufficient number of good slices after that bad setor**. If par2j supports scanning beyond the bad portion of files, there will be no need to use any 3rd party utility like DDRescue-GUI.

I have [attached](https://mega.nz/file/m1QxgKJL#dVV9Nv1A7DrRxDM5XGRD_cMFxa9SumdpkgGAYqoos0A) the MultiPar Verification Logs (both when the file is on bad sectors and after recovering it from bad sectors) along with the DDRescue-GUI logs (open them with [ddrescueview](https://sourceforge.net/projects/ddrescueview/) to view bad portions of files graphically).

By the way, there are several utilities like [FileSaver](https://www.medo64.com/filesaver/), [Dust Signs File Copier](https://www.andreas-unterweger.eu/software/file-copier/), [Roadkil’s Unstoppable Copier](https://www.roadkil.net/program.php?ProgramID=29), [Bad Block Copy for Windows](http://alter.org.ua/soft/win/bb_recover/), [SalvageFile](https://github.com/rasberry/SalvageFile), [badcopy](https://github.com/bad-copy/badcopy) etc to recover maximum part of files from bad sectors.

Thanks in advance...

**Comment by Yutaka-Sawada** [comment]
> If par2j supports scanning beyond the bad portion of files, there will be no need to use any 3rd party utility like DDRescue-GUI.

I understand what you want. Someone requested the same feature ago. While I tried at very early version, it skipped an error block and resumed from the next block. But, it was difficult to test possible error case. Now, it stops the reading at the first read error (bad sector). It still show result of verified files, even when there is a file access error.

Though you can verify files on a bad drive, you should not repair damaged files there. Becasue par2j tries to repair a damaged file on the same drive, it may happen to put file data on another bad sector. You would better copy damaged files from a bad drive to a good drive at first. To retrive a damaged file on a bad drive, you may use a recovery tool, which you listed. So, your example usage is good.

I did not implement the full scanning after bad sector, because there are many tools for such purpose already. You can use your favorite tool, which is well tested by many users. For example, when your PC is broken, you will ask an expert to retrive the data. Better leave it to a specialist.

**Comment by swarup459** [comment]
> Becasue par2j tries to repair a damaged file on the same drive, it may happen to put file data on another bad sector.

That's a valid reason not to implement the feature. I asked for it as a _'nice to have'_ feature rather than _'need to have'_. Anyway, this thread will be useful for others as some good Bad Sectors recovery programs are listed. And, thanks for the early reply as usual.
