### ISSUE TITLE
archive (split) and create recovery files

### ISSUE THREAD

**Issue by copenhaus** [Yutaka-Sawada/MultiPar#48]
- pick a file, right-click and select "archive and create recovery files"
- in 7ziip "Add to Archive" interface, put a number that is smaller than your file in "Split to volume bytes", click "Create SFX archive"
- when 7zip is done, MultiPar GUI shows up, but it only shows the first (exe) file to recover

**Comment by Yutaka-Sawada** [comment]
The right-clicked feature "archive and create recovery files" is made for a single archive file. It doesn't work with splited archive files, because it cannot get resulting filenames in 7-Zip. I'm sorry for this limitation.

When you want to make PAR2 files for multiple files, manually open MultiPar after you archive (and split) files by 7-Zip. Then, add files (main SFX and splited files) on MultiPar's window.

**Comment by copenhaus** [comment]
Arigato.
