### ISSUE TITLE
Weird bug with large collection of many files

### ISSUE THREAD

**Issue by abiphone** [Yutaka-Sawada/MultiPar#49]
I've encountered some weird bug when selecting a large base folder with many files.

See the image below:
![Screenshot 2021-11-27 235912](https://user-images.githubusercontent.com/50788307/143688403-eab01be3-8de1-425a-b451-78f20ad2ff1a.png)

These are automatically selected options. Multiplying the block count and block size give rise to a number larger than the total data size, same goes to the recovery data size at 3.07%.

This does not occur to a single large file:
![Screenshot 2021-11-28 001242](https://user-images.githubusercontent.com/50788307/143688777-14d868f5-7c7d-4894-a470-6e9891d4b2bf.png)

**Comment by Yutaka-Sawada** [comment]
Thank you for reporting the strange behavior. The automatic selection worked badly. It tried to set 3000 block count by default. Because the number of files exceeds 3000, it failed to find a good block count. You can solve this problem by changing MultiPar option manually. I’m sorry for the inconvenience.

Open "MultiPar Options" window. There is an item "Limit Block count up to" in "Block allocating method" section on "GUI options" tab. When you want to remove the limit number, un-check the option. Or, you may increase the limit number to be more than number of files. When there are many source files, it needs much more blocks to perform good efficiency. Note, as you set more blocks, the speed will become slower.

**Comment by abiphone** [comment]
Makes sense and thanks for the help!

I suggest adding a GUI option to limit the recovery data size to no larger than the total data size. A recovery size twice the total data size is pretty weird.
