### ISSUE TITLE
GUI create with batch automatically doesn´t work

### ISSUE THREAD

**Issue by prdp19** [Yutaka-Sawada/MultiPar#5]
Hi,

i want to start the GUI with batch and set it up so that it starts directly.

But it doesn't matter if I do
`START "" %MULTIPAR% /create "%SOURCEDIR%"`
or
`%MULTIPAR% /create "%SOURCEDIR%"`
use.

In both cases the GUI opens but does not start automatically. Why?

I always have to press the Create button myself.
Unfortunately, I cannot automate this.

Is there a solution or do I have to use par2j64.exe?

I would like to use the GUI because you can do it easily
- Set yEnc block size and limit (i would use 5000)
and GUI also sets the values 
​​- block count
- Recovery blocks and recovery files automatically on (based on the source files)

Thanks for the tool!
Greetings

**Comment by Yutaka-Sawada** [comment]
> In both cases the GUI opens but does not start automatically. Why?
> Is there a solution or do I have to use par2j64.exe?

GUI is used for manual setting. If you don't change setting and want to start creation automatically, you should use PAR2 client (par2j64.exe) directly. The setting you set on MultiPar GUI is possible to be options for par2j64.exe, too. MultiPar GUI sends command to par2j64.exe. You may see such command-line options by saving log. There is a help document "Command_par2j.txt" in "help" folder of MultiPar. I wrote "Batch script" samples in MultiPar's Help also. You may refer them.

Though MultiPar GUI sends all source file names, par2j64.exe can accept a folder name for them. You may use "Trial" command to see how are the result.

**Comment by prdp19** [comment]
Hi,

many thanks for the answer.

I actually use par2j64.exe too
`%PAR2% c /sm2048 /rr10 /rd1 /rf3 "%SOURCE%.par2" *`
and it works. Unfortunately, I use different file sizes.

MultiPar.exe selects the settings (above c. and d.) based on the selected source files. So MultiPar.exe *calculates something, par2j64.exe don´t. Can par2j62.exe do the same? If yes, how?

Then I ask differently how do I set the following parameters of the GUI via command line (par2j64.exe)

a.) restrict block size for yEnc (3000-5000) [static] - which command? maybe /sm?
b) block count limit (3000-5000) [static] - which command? maybe /sm?
c.) number of recovery blocks [based on source filesize, not static] - i know its */rn<n>
d.) number of recovery files [based on source filesize, not static] - i know its */rf<n>

a.) and b.) is static, which commands are intended for this? 
In the Command_par2j.txt I don't find any information or am I blind?

And how do I set the parameters for c.) and d.) based on *source files, not static.
What do I have to charge if necessary? What is the formula that MultiPar.exe uses?

I hope I was able to make it clear what I want to implement.

The command /rr<n> is necessary for the redundancy, its can static, that is clear to me ;)

**Comment by prdp19** [comment]
Many tries later... i think this is the best dynamic setting?

`%MULTIPAR% c /uo /rr10.5 "%SOURCEDIR%\%FILENAME%.par2" *`

It not, tell me.

**Comment by Yutaka-Sawada** [comment]
> Can par2j62.exe do the same?

Yes, you can set all setting of MultiPar GUI by command-line also. I use same initial setting method in both MultiPar GUI and PAR2 client. 

> a.) restrict block size for yEnc (3000-5000) [static] - which command? maybe /sm?

Yes, use "/sm" option.
yEnc 3000 Lines = 384,000 bytes. command-line option is "/sm384000"
yEnc 5000 Lines = 640,000 bytes. command-line option is "/sm640000"

> b) block count limit (3000-5000) [static] - which command? maybe /sm?

When you didn't change MultiPar option "Block allocating method" manually, default setting is "/sr10 /sn3000" (These are same as Rate (count / size) = 1% and Limit Block count up to = 3000). 
If you set limit to 3000, command-line option is "/sr10 /sn3000". (default setting, can omit)
If you set limit to 5000, command-line option is "/sr10 /sn5000".

> c.) number of recovery blocks [based on source filesize, not static] - i know its */rn<n>

If you want to set static number in batch file, "/rr" option is good instead of "/rn". The "/rr" option calclates number of recovery blocks based on number of source blocks. That is the way, which MultiPar GUI do.

> d.) number of recovery files [based on source filesize, not static] - i know its */rf<n>

This depends on which setting you set on MultiPar GUI. Use "/rd" option to select which Sizing scheme. If you use "Variable size" Sizing scheme on MultiPar GUI, the number of recovery files is calculated automatically. If you use another Sizing scheme on MultiPar GUI, set an option "/lr0" to limit size of the largest recovery file. Basically you don't need to set "/rf" option, unless you want exact number of files.

> i think this is the best dynamic setting?
> `%MULTIPAR% c /uo /rr10.5 "%SOURCEDIR%\%FILENAME%.par2" *`

If you want "yEnc 5000 Lines", "Limit 5000 blocks", and Same size recovery files;
`%MULTIPAR% c /uo /rr10.5 /sm640000 /sr10 /sn5000 /rd0 /lr0 "%SOURCEDIR%\%FILENAME%.par2" *`

If you want "yEnc 3000 Lines", "Limit 3000 blocks", and Variable size recovery files;
`%MULTIPAR% c /uo /rr10.5 /sm384000 /rd1 "%SOURCEDIR%\%FILENAME%.par2" *`

By the way, you don't need to set "/uo" option normally. The UTF-8 setting is used for MultiPar GUI's parser mostly. MultiPar GUI need to know which character encoding is used.

Be careful to use wildcard `*` in batch script. It will search all files in the %SOURCEDIR% directory. When there are (previous created) %FILENAME%.par2 already, it will include them as source files again. If your source files have something common filename or extension, it's safe to set them. Such like `*.mp3` or `*.zip`. Or you may set deny list by "/fe" option, when you want to exclude some file types.

**Comment by prdp19** [comment]
Thank you, Yutaka!

I think the best solution for me is

%MULTIPAR% c /rr10.5 /sm640000 /rd1 "%SOURCEDIR%\%FILENAME%.par2" *.rar

**Comment by prdp19** [comment]
%MULTIPAR% c /rr10.5 /sm640000 /rd1 "%SOURCEDIR%\%FILENAME%.par2" *.rar 
is much slower then 
%MULTIPAR% c /uo /rr10.5 "%SOURCEDIR%\%FILENAME%.par2" *

Its the reason /sm640000 or /rd1 or both?

**Comment by Yutaka-Sawada** [comment]
> Its the reason /sm640000 or /rd1 or both?

I'm not sure. "/rd" option doesn't give speed difference. "/sm" option may affect number of source blocks. As source blocks are many, creation will be slow. But, it should not cause large speed difference, when number of blocks is limited. Use Trial command to see the difference of block count.

**Comment by prdp19** [comment]
What is best for dynamic par2 files (for Usenet)?

`/sm384000` (Isn't that default?)
or 
`/640000`

Thanls!

**Comment by Yutaka-Sawada** [comment]
> /sm384000 (Isn't that default?)

No, it's not a default setting. You need to set the option manually for Usenet article size. When you omit "/sm" option, there is no restriction in block size. Though I don't know well about Usenet, how many lines to set depends on the server. You should follow your using Usenet server's direction.

> Is there anything else I can improve?

If you have a fast GPU, you may try GPU acceleration for speed. Because it cannot determine a user's GPU is fast or slow, MultiPar GUI disable the feature by default. (Intel CPU's integrated GPU is slow.) When you use GPU, add "/lc32" option. Causion, using GPU will cause your PC to be heavy and very hot.

**Comment by prdp19** [comment]
> 
> 
> > /sm384000 (Isn't that default?)
> 
> No, it's not a default setting. You need to set the option manually for Usenet article size. When you omit "/sm" option, there is no restriction in block size. Though I don't know well about Usenet, how many lines to set depends on the server. You should follow your using Usenet server's direction.

Standard is 3000, most accept up to 5000.
Which settings are the best for this?

> > Is there anything else I can improve?
> 
> If you have a fast GPU, you may try GPU acceleration for speed. Because it cannot determine a user's GPU is fast or slow, MultiPar GUI disable the feature by default. (Intel CPU's integrated GPU is slow.) When you use GPU, add "/lc32" option. Causion, using GPU will cause your PC to be heavy and very hot.

Oh no, my gpu isnt good ;)

Thanks!

**Comment by Yutaka-Sawada** [comment]
> Which settings are the best for this?

I don't know. You would better ask the question in UseNet users' community.

**Comment by prdp19** [comment]
Okay. On last question:

How can i set the option
`Don´t wait finish of other task`
from GUI?

**Comment by Yutaka-Sawada** [comment]
> How can i set the option
> Don´t wait finish of other task

par2j.exe doesn't have such option on MultiPar GUI, because Command Prompt has the feature already.

When you type multiple .EXE filenames on Command Prompt or in batch file, they run one by one. 
For example, there are 2 .EXE files.
```
something1.exe
something2.exe
```
something1.exe runs at first. After it finished, something2.exe runs next. So, it waits finish of previous command.

If you don't want to wait a finish, use "start" command. You may refer the usage details on Internet.
For example, you run 2 .EXE files in same time.
```
start something1.exe
start something2.exe
```
This runs something1.exe at first, and next runs something2.exe without waiting the finish. Be careful to process multiple heavy task at once, as they may consume PC resource.
