### ISSUE TITLE
Report "All Files Complete" as final status even if "PAR File(s) Incomplete"

### ISSUE THREAD

**Issue by Safihre** [Yutaka-Sawada/MultiPar#54]
If Multipar detects some bogus par2 files that might have a similar filename but don't belong to the set, it's final words are `PAR File(s) Incomplete`, even if the verification of the files was successful.
For our automatic parsing this is very confusing, as we don't know if verification of the actual files was sucessful.
Would it be possible to report `All Files Complete` on top of `PAR File(s) Incomplete` if verification was successful?

**Comment by Yutaka-Sawada** [comment]
> Would it be possible to report All Files Complete on top of PAR File(s) Incomplete if verification was successful?

This is easy to change. When I made the output format long ago, I thought that "All Files Complete" might be bad, because some PAR files were incomplete. Then, it printed either text exclusively. To parse the output, printing each line may be good.

I made a sample PAR clients of the new output style. I needed to change my GUI (MultiPar.exe). Someone may need to change his parser, too. If nobody complains this style, this is adapted in the next release.

I put the sample version (MultiPar_sample_2021-12-31.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). You may test the behavior. I fixed a bug in my PAR1 client also. If someone sees a mistake in ExitCode or somewhere, please report with ease.

**Comment by Safihre** [comment]
Thank you, this works for us!
