### ISSUE TITLE
Crash when using `-vs2 -vd`

### ISSUE THREAD

**Issue by Safihre** [Yutaka-Sawada/MultiPar#55]
I am writing unittests for our parsing of the output of Multipar. Therefore I created a test set that includes a number of things that we know happen in the real world with our application.
However, to my surprise, Multipar just crashes after searching for misnamed files in this test set.
I found that it only breaks if I include the `-vs2 -vd` parameters, which we do for performance on multiple verification runs.

This is the test-data: [par2repair.zip](https://github.com/Yutaka-Sawada/MultiPar/files/7796437/par2repair.zip)
This is the command I use:
```
C:\Users\safihre\Documents\GitHub\sabnzbd3\win\multipar\par2j.exe r -uo -vs2 -vdC:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp C:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp\par2test.par2 C:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp\*
```
This is the last bit of output, and then it just stops:
```
Verifying Input File   :
         Size Status   :  Filename
            = Complete : "par2test.part1.rar"
            = Complete : "par2test.part2.rar"
            - Missing  : "par2test.part3.rar"
            - Missing  : "par2test.part4.rar"
            8        0 : "par2test.part5.rar"
            = Complete : "par2test.part6.rar"

Complete file count     : 3

Searching misnamed file: 3
         Size Status   :  Filename
       102400 Found    : "foorbar.rar"
            = Misnamed : "par2test.part3.rar"
```

I tried both version 1.3.1.8 and the test-version you made earlier today.

**Comment by Yutaka-Sawada** [comment]
There might be a conflict in file access. Though I could not re-produce the incident, I found some strange points in the command-line.

(1) Saving folder should be different from searching folder.
 You set the same directory as base directory; "-vdC:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp". 
So, writing on the verification result and checking files may happen to lock a same file. If it tries to write a data on a file while reading the file, it will cause access violation error.

 So, set another directory. Such like "-vdC:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\save". 
Don't set a child folder in base directory, because it may search inner folder later.

(2) External files should exist in different directory from base directory.
 You set external files; "C:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp\*". 
This may cause double finding same files. Setting external files is made to select other files in different directory. If you want to search all files in the base directory, use "-vl2" option instead.

 Then, the command-line would be like;
```
par2j.exe r -uo -vl2 -vs2 -vdC:\Users\safihre\Documents\GitHub\sabnzbd3\tests\save C:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp\par2test.par2
```

 If you won't be able to solve the problem by changing these 2 points, I might mistake something. As I'm lazy, I didn't write error message so much. Maybe I didn't think that an error should have not happened. Anyway, please try the 2 point at first.

**Comment by Safihre** [comment]
Good suggestions, I implemented them. The command is now:
```
C:\Users\safihre\Documents\GitHub\sabnzbd3\win\multipar\par2j.exe r -uo -vs2 -vdC:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache C:\Users\safihre\Documents\GitHub\sabnzbd3\tests\cache\par2repair_temp\par2test.par2
```
But still, crash..

**Comment by Yutaka-Sawada** [comment]
Your command-line uses par2j.exe (32-bit version .EXE). Is there difference with par2j64.exe (64-bit version .EXE) ? I test with 64-bit version normally. 

The command-line is for Reapir. Is verification possible ? Did it crash at repair only ? or at verification also ?

To find a wrong point in my source code, more information is helpful. I need to review my old code.

**Comment by Safihre** [comment]
You are right, with the 64bit version it works! Strange!
The 32bit also crashes with just verification flag.

**Comment by Yutaka-Sawada** [comment]
Thank you for the tests. From my experience, unknown odd behavior may come from stack ovefflow. I found a wrong point in my source code. I had kept five 32-bit integers to store seven 32-bit integers. I might forgot to increased size after using more number of integers later. 64-bit version .EXE may happen to avoid the fault by their integers' alignment. Anyway, I fixed the bug now.

I put the sample version (MultiPar_sample_2022-01-02.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). You may test the behavior. If someone sees a failure or strange result, please report with ease. I will solve as possible as I can.

**Comment by Safihre** [comment]
It works now, thank you.
