### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by eddilara** [Yutaka-Sawada/MultiPar#57]
we really need a batch recovery option 
like what parbuddy and Par2MultiChecker Ultimate Edition can do.....

**Comment by Yutaka-Sawada** [comment]
I did not know about [ParBuddy](https://par-buddy.software.informer.com/) or [Par2MultiChecker](https://sites.google.com/site/tsdarkness/par2multichecker). They seems to have a queuing recovery feature. If you want a batch recovery, you may write a batch script or use a special tool like them. I think that MultiPar should be a simple basic tool. When other developers make their tools for another special usage, I don't need to make such tool.

**Comment by eddilara** [comment]
it would be very nice to have this feature....
and yes I know you could use a batch file....but we shouldn't really have to write a batch file just to recover a folder full of par2 files
if we could drag and drop a folder into multipar ..and have it understand that it should fix all the files in that folder ...that would be good enough
or have multipar be able to monitor a folder for par2 files to check

**Comment by JohnLGalt** [comment]
Under Client Behavior tab, there is the Verification and Repair options:, which has Monitor files to verify and repair automatically, *and* a check box to no search subfolders.

Does that not work? It used to....

**Comment by Yutaka-Sawada** [comment]
If it can be a simple tool, I may consider to make. You did not say the detail at all. Please explain your environment and usage. How to use the tool for what usage. I don't know the usage of ParBuddy or Par2MultiChecker. I don't know what feature you want to use. I cannot make anything, while I don't image what to make.

For example, drag & drop a folder only ? Multiple folders or PAR2 files, too ? Do you add another folder or file later ? Does the folder includes source files also ? The content (PAR2 files) in the folder are constant or variable by time ? How many files in a folder ? Do you see the progress of batch processing ? Do you control the queue (pause, cancel, abort, change order, etc) ? What result does each process show ? Will it retry again, if a recovery set verified incomplete source files ?

Post minimum required utility is good. If you want a rich tool with many features, I'm lazy to make such one, hehe.

**Comment by eddilara** [comment]
I need a new tool cause parbuddy is getting old and outta date...and the other tool is paid
I want the ability to recover and fix all the files in a folder without having to click on each par file to do it
https://images2.imgbox.com/27/4b/r2lnSHNH_o.png
if multipar could just automatically fix all the files in a folder without having to click each file...that would be probably enough

**Comment by Yutaka-Sawada** [comment]
I'm trying to make a new tool, as a programming practice. It calls par2j64.exe for repair, as same as MultiPar does. Because the result is Exit Code of par2j, you cannot see details. You will need to open MultiPar to confirm the result.

When you drag & drop a folder on a window, it will search PAR2 files in the folder. I made a window application, which is drag & drop acceptable. Now, there is a problem. How to distinguish a PAR2 recovery set from other sets ? Does each recovery set include PAR2 index file ?

If PAR2 index file exist always like below, it's easy to check. By removing files with `.vol#+#.par2`, it can get filename of index files only.
```
somebody.par2
somebody.vol#+#.par2
someone.par2
someone.vol#+#.par2
something.par2
something.vol#+#.par2
someday.par2
someday.vol#+#.par2
somewhere.par2
somewhere.vol#+#.par2
```

How many PAR2 recovery sets in a folder ? Do you want to see each result independently ? If files are more than a window size, resulting text requires scrolling. The result may be simple lines like below.
```
somebody.par2 ... source files are complete
someone.par2 ... repaired succeefully
something.par2 ... need more blocks to repair
someday.par2 ... processing now
somewhere.par2 ... waiting
```

**Comment by eddilara** [comment]
probably 80% of the time the index file is there
as for how many might be in a folder...that really depends on how many files Ive downloaded from newsgroups....it could be 1 or it could be a few hundred...but they all have their own par2 set
(I download alot of anime)
if the application can just verify that the file set was fixed and is good...that enough

**Comment by Yutaka-Sawada** [comment]
> probably 80% of the time the index file is there

It may be difficult to distinguish PAR2 recovery set each other, when there are different filename format. I made a current sample to test searching behavior. It doesn't check PAR2 file yet, but get filename only.

I put the sample (ParQueue_sample_2022-01-13.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). You may test the behavior. If it cannot find a PAR2 file in the same recovery set, or fail to find any PAR2 files of a recovery set, it's a bug. I don't know that how are the PAR2 filenames on your environment. If you see a bug, please report their filename examples.

**Comment by eddilara** [comment]
seems to work

**Comment by Yutaka-Sawada** [comment]
I fixed some bugs and improved the process. You may pause, cancel, or restart the queue by Key input. You may Drag & Drop another folder after queue end. I feel that current one may have enough quality for practical usage.

Key type is same as MultiPar GUI. Pushing Pause-key will pause the next task, and push again to resume. It doesn't stop the current task. Pushing Escape-key will cancel all following tasks in the queue. After cancel, you can Drag & Drop another folder. This is useful, when you happened to drop a wrong folder, hehe. Pushing F5-key will restart the queue again, when you finished already. Becasue this restart will skip complete recovery sets in the current queue, the process will become faster than Drag & Drop a same folder again.

I put the sample (ParQueue_sample_2022-01-15.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). If you see a bug, please report the detail. If someone wants another feature or utility, I may consider the difficulty.

**Comment by eddilara** [comment]
nice...now it needs a auto update feature  :)

**Comment by Yutaka-Sawada** [comment]
> it needs a auto update feature

I don't want to add online update feature in my tools. Because I mistake sometimes, using beta version has risk. Normal users should update, when it will be tested enough.

> a right click context menu or buttons at the top

I'm not sure what they are. When you request something, please say the details. I don't have a telepathy skill. In English, [Five Ws and How](https://en.wikipedia.org/wiki/Five_Ws) is important.

**Comment by eddilara** [comment]
I just mean a right click menu either that or buttons at the top to do various things in the program

**Comment by Yutaka-Sawada** [comment]
> a right click menu either that or buttons at the top

 Top of what ? Where is the right click menu ? Where are buttons ? How do you use them why ? Sample hand drawing picture may be helfpul.

> to do various things in the program

 What things will you do ? There are relationship of supply and demand. I cannot make a supply, while I don't know the demand.

**Comment by JohnLGalt** [comment]
@Yutaka-Sawada What @eddilara is asking for is a method to invoke this batch monitor and recover process from either a context menu (I presume that means on a files, or, more appropriately, on a folder) or else easy to use buttons at the top of MP to invoke the same.

At the very least, being able to right click on a folder to monitor all .par files in the folder for batch processing would definitely be good, assuming this feature actually works that way.

@eddilara can probably explain it better, but I believe that is the gist of it.

**Comment by Yutaka-Sawada** [comment]
Thanks John L. Galt for the explanation. Normally I implement a requested feature, only when the requester helped the development. Sometimes I cannot test myself. But, I implemented a way to open ParQueue.exe, because it was easy.

Now, you may open ParQueue by using MultiPar's icon or short-cut. When MultiPar gets a folder at starting, it checks the content. If there are multiple PAR2 files in the folder, it will invoke ParQueue.exe instead of opening MultiPar's Create window.

I put the sample (ParQueue_sample_2022-01-20.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). To open ParQueue from MultiPar, you need to change some options. You should read ReadMe.txt before test. (I will write a manual for ParQueue.exe later.) If you see a bug, please report the detail.
