### ISSUE TITLE
Incorrect handling of files with name with trailing period

### ISSUE THREAD

**Issue by d4nyl0** [Yutaka-Sawada/MultiPar#58]
Hi,
MultiPar works unpredictably with filenames with a trailing period .

Steps to reproduce errors:
Create a new directory ("TestPar2") whit a filename "test." inside it (with Windows probably you can't, but if you create/rename it with CygWin you will do; or if you have a backup from Android/Unix/Linux you can find filenames with a trailing period) and put easy text inside the file ("one two three").

**Strange behaviour n.1:**
* Open MultiPar GUI and try to create a parchive for this directory
* Hit "Create" button --> you get error message "_input file is not found, test_"
The strange behaviour is: can't handle filenames with trailing period.

**Unexpected behaviour n.2:**
* par2j64.exe c test.par2 * --> _Created successfully_
The unexpected behaviour is: GUI can't handle that filenames, but command line does (it's powerful, my favourite!)

**Strange behaviour n.3:**
* Open GUI and try to verify test.par2 --> it wants to rename "test." to "test"
Ok, here it is coherent with the design, but unexpected.

**Strange behaviour n.4:**
* Try to verify test.par2 from command line --> "_Ready to rename 1 file(s)_"
It is unexpected, because command line created that parchive from that source file, and now it wants to rename it.

Tested with version 1.3.1.9

Please, let me know if I could help.
d4nyl0

**Comment by Yutaka-Sawada** [comment]
Such filename (period at the last) is invalid on Windows OS. I needed to use [a renaming tool](https://github.com/Yutaka-Sawada/Rename7) to make sample filenames. By adding "\\\\?\\" in front of full path, I could rename them to safe name. Because I'm lazy to type everytime at tests, I implemented sanitize feature in the renaming tool.

Now, I'm not sure how to treat such invalid filenames. I made my tool to be avoiding invalid filenames. So, the current par2j 's behavior is mistake. I forgot to check invalid filenames or sanitize them. Because most users don't see such filenames on Windows OS, nobody complained the behavior.

What solution do you want ? From PAR2 specifications, it is recommended that users are warned when they create PAR files with names that are incompatible with Windows, Mac, or Linux systems. You were not warned, that was my mistake. Do you think that par2j and MultiPar GUI should handle such filenames ? Such like; creating PAR file for them, verifying or repair them.
