### ISSUE TITLE
Uneditable Recover Files Path UI problem

### ISSUE THREAD

**Issue by huhiha** [Yutaka-Sawada/MultiPar#6]
There should be a way to directly edit the Recovery Files Path. 
Now the path is not editable. If you press Browse, you still have to navigate into the folder by mouse, which is overwhelming if the path is deep. 

BTW, same as the Base Directory Path when you open a *.par2 file. 

There are 2 possible solutions either of which can solve this problem:

1. Make the Recovery Files Path editable.

1. After pressing the Browse button, the window coming out shall contain an address bar. 

 

![Image of Yaktocat](https://i.postimg.cc/5tV3d9Z0/1.png)

**Comment by Yutaka-Sawada** [comment]
> There should be a way to directly edit the Recovery Files Path.

I'm not sure the problem. I thought that selecting folder might be easier than typing folder name. (a user may miss-type a directory name.)

> There are 2 possible solutions either of which can solve this problem:
> 1. Make the Recovery Files Path editable.

This is difficult, because it's hard to know when the edit finish. The path must exist. While a user is typing a directory, the intermediate name doesn't exist. So, it needs to wait, and check the path after finishing the type. It's hard to know the timing.

> 2. After pressing the Browse button, the window coming out shall contain an address bar.

I tested this, because the dialog (SHBrowseForFolder) has the EditBox feature (BIF_EDITBOX). I enabled the EditBox feature. It shows current selected folder's path. You may edit the path manually. When the edited path is invalid, it doesn't accept the wrong path. Thus, the "Browse" button returns valid path always.

I put the sample (gui_sample_2020-07-21.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu).

**Comment by huhiha** [comment]
Thanks for the quick respond. I downloaded that sample and I think that will do the job.

**Comment by Yutaka-Sawada** [comment]
I see. If there is a problem, please report again. Or else, I will release the change at next version.
