### ISSUE TITLE
MultiPar 1.3.2.2 is getting blocked by antivirus programs

### ISSUE THREAD

**Issue by didamsko** [Yutaka-Sawada/MultiPar#61]
A heads up that the recent MultiPar 1.3.2.2 is triggering anti virus software like Avast, AVG and McAfee. 

Spotted your MultiPar 1.3.2.2 release today so downloaded and updated from MultiPar 1.3.2.0 to MultiPar 1.3.2.2 but on first run the new release got blocked by Avast and moved to the virus chest as "FileRepMalware". 

I assume that this is a false positive but now you know that it is giving problems. I used the portable "MultiPar1322.zip" version of MultiPar 1.3.2.2.  The file hash matched. 

I uploaded the "MultiPar.exe" to VirusTotal where 5 security vendors and no sandboxes flagged the file as malicious: https://www.virustotal.com/gui/file/c4d947c4524cf392573984ff6c0062a641ea356661191a9d9fe7e2934f6f62ad

**Comment by didamsko** [comment]
PS. it seems that the issue with Avast got introduced with version 1.3.2.1, that one also gets flagged as malicious by 5 security vendors on VirusTotal: 
https://www.virustotal.com/gui/file/c4d947c4524cf392573984ff6c0062a641ea356661191a9d9fe7e2934f6f62ad

Avast has no issues with MultiPar 1.3.2.0

**Comment by didamsko** [comment]
Had a closer look and Avast has no problem with MultiPar 1.3.2.1. So problem seems that have gotten introduced with MultiPar 1.3.2.2.

**Comment by Yutaka-Sawada** [comment]
Thank you for the report. I confirmed the result on VirusTotal. I updated compiler from [Visual Studio 2019 version 16.11.9 to version 16.11.10](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.11.10). I re-compiled MultiPar.exe by incrementing version to 1.3.2.3. All source code is same except the version number.

MultiPar.exe (version 1.3.2.2)
5 security vendors and no sandboxes flagged this file as malicious
(Avast, AVG, BitDefenderTheta, McAfee, SecureAge APEX)

Newly compiled MultiPar.exe (version 1.3.2.3)
2 security vendors and no sandboxes flagged this file as malicious
(BitDefenderTheta, SecureAge APEX)

So, it was false positive. If those security vendors found soemthing malicious behavior in the .EXE file truly, it should find it from new version samely. I cannot solve this problem, because it's a fault of them. I put my tested .EXE files (MultiPar_comparison_2022-02-12.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). You may see the difference with a binrary editor.

**Comment by didamsko** [comment]
Thanks for looking into it. I tried using the 1.3.2.2 release after replacing the old MultiPar.exe with the re-compiled one but Avast then also removes that one: 

![untitled](https://user-images.githubusercontent.com/60958082/153710512-977994d8-e6a3-4aa5-98ae-e01c54b4a433.JPG)

On VirusTotal also previous 1.3.2.0 and 1.3.2.1 releases (i did not go back further) get flagged as malicious by BitDefenderTheta
and SecureAge APEX but that was not a issue i think as they are too obscure. Avast/AVG and McAfee have a lot of home users so the issue will start popping up. 

Is it an option to release a 1.3.2.3 version that will not get blocked? As you show the re-compiled MultiPar.exe does not get flagged on VirusTotal by Avast/AVG and McAfee but somehow in combination with the 1.3.2.2 release package it still gets blocked.

**Comment by Yutaka-Sawada** [comment]
I'm not sure which action is flaged as FileRepMalware for Avast/AVG/McAfee. Becasue I don't know what is wrong, it's difficult for me to solve the problem. You should ask to Avast why it's thought as harmful.

**Comment by didamsko** [comment]
OK thanks. I send a report to Avast that them flagging it as "FileRepMalware" is a false positive so that they can have a look. And then restored and added the 1.3.2.2 "MultiPar.exe" as exception to prevent Avast from deleting it: 

![untitled](https://user-images.githubusercontent.com/60958082/153713228-a6c82872-ed8e-42fc-bffe-7d3e2bd7fcb8.png)

Hope that Avast/AVG will correct this false positive soon. Otherwise i will keep contacting them if it happens again on future MultiPar releases.

**Comment by didamsko** [comment]
PS. i saw that there is a option at Avast for software developers to get software whitelisted to reduce the risk of false positive detection. Maybe that is something to consider if the issue keeps repeating:  

https://support.avast.com/en-us/article/229/

**Comment by Yutaka-Sawada** [comment]
I read an article "[Avast Threat Labs - Clean guidelines](https://support.avast.com/en-us/article/228/)". If the blocking started at MultiPar.exe version 1.3.2.2, the new feature "/batch command" might be bad.

From Avast 's guidelines;
Program functionality
Prohibited
1. Transparency and attribution
A program must not fail to clearly indicate when the program is active, and must not attempt to hide or disguise its presence.

When "/batch command" is enabled, MultiPar.exe starts in background silently, and finishes repair automatically. That behavior may look like a hidden spy for Avast. But, I'm not sure. If you have time to test, I will be able to remove this feature and make a sample .EXE file.

**Comment by didamsko** [comment]
I'm available to test. When going by the changelog there are two new features in 1.3.2.2: 

GUI update - New - I added /batch command to MultiPar.exe for batch scripting.
PAR2 client update - New - A new option was added to remove recovery files.

You also mention "I added a feature to purge PAR2 files in my PAR2 client. Though I don't use such **risky feature**, [it was requested for batch repair](https://github.com/Yutaka-Sawada/MultiPar/issues/59)." 

Could it be that that has to do something to do with it?

**Comment by Yutaka-Sawada** [comment]
> Could it be that that has to do something to do with it?

Because PAR2 client is par2j64.exe, it doesn't affect MultiPar.exe. I don't know what was bad. So, I wanted to test one factor at first. I made a sample, which don't have "/batch command" feature.

I put the sample file (gui_sample_2022-02-13.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Though it's not flagged as malware on VirusTotal mostly, I don't know how Avast detects. Please test it.

**Comment by Yutaka-Sawada** [comment]
Thank you for test. I remove the "/batch command" feature at the next release. Anyway most uers won't use the automation. When someone wants batch operation, he may use command-line version par2j64.exe. If you see another problem or my fault, please report with ease.

**Comment by didamsko** [comment]
It might be good idea to release a version of MultiPar 1.3.2.2 without the problem MultiPar.exe soon and then remove the original download. Although the current MultiPar 1.3.2.2 release itself is not malicious it most likely will keep triggering peoples antivirus programs.

**Comment by Yutaka-Sawada** [comment]
Because different .EXE files of same version may confuse users, I released v1.3.2.3 today. But, some other security vendors still detect something. I don't know what is a factor for them.

**Comment by Yutaka-Sawada** [comment]
I found that changing unused area in DOS header of .EXE files might be bad. I will change text area of .EXE files to edit CRC-32 at next versions. It's interesting that security vendors check PE's header area to recognize malware.

**Comment by didamsko** [comment]
Well looks like this will need some more work. Case of Murpey's Law i'm afraid. 

Just spotted your v1.3.2.3 release that should have fixed the problems but now Avast started flagging the "ParQueue.exe" as "Win32:Malware-gen" :-( 

It goes so far that the Avast Web Shield will not even allow me to download the "MultiPar1323.zip" or "MultiPar1323_setup.exe" releases: 

![parqueue](https://user-images.githubusercontent.com/60958082/154224435-6bda710b-1233-437d-a937-972867d3e492.JPG)

I also no longer can download the v1.3.2.2 release

This is the v1.3.2.1 "ParQueue.exe" on VirusTotal: 
https://www.virustotal.com/gui/file/9dcf09271c5b041fa17a4a3a426770fe952ba61bbeb2fdfc16b6961919a8f01f

This is the v1.3.2.2/v1.3.2.3 "ParQueue.exe" on VirusTotal: 
https://www.virustotal.com/gui/file/512cc34030d5471adb7ad0e5f5d3e6241b9fe8f90409ca66ae2941fc0c7e95b9

Hope you have time to look into this. Sadly i can not be of much help as i'm not a programmer myself.

**Comment by Yutaka-Sawada** [comment]
I heard that setting VERSIONINFO in resource might decrease false positive. Because I was lazy to update them at every version, I didn't set the resource. I changed the implementation of version number. I added VERSIONINFO in all my applications. Then, most security venders don't miss detect. But, this is something like foolish... why adding VERSIONINFO can avoid false positive ? It seems that some security venders are lazy to see real behavior.

Avast was not so lazy, but it may not like automation tool. I added menu in ParQueue.exe for manual control. Though it's same behavior as keyboard control, Avast seems to say OK. I don't know how it recognizes.

I put the sample file (MultiPar_sample_2022-02-16.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Though it's not flagged as malware on VirusTotal mostly, there are some false positive still. This may be a good measure to see their quality.

**Comment by didamsko** [comment]
Thanks. The changes you made seem to fix the problem. First positive was that i was able to download the "MultiPar_sample_2022-02-16" without issues. Then i replaced the v1.3.2.2 version with the "MultiPar_sample_2022-02-16" files. First run triggered the Avast "suspicious file detected" scan but after that program is running fine. 

Fingers crossed that no more complications arise.
