### ISSUE TITLE
Estimated recovery file size too high

### ISSUE THREAD

**Issue by XenonR** [Yutaka-Sawada/MultiPar#68]
Hi, thanks for this application. I use it quite often without issues (great job!). Now I stumbled upon what appears to be a bug.
I have tested this with 1.3.1.9 and the latest 1.3.2.4 beta. Have a look:
![grafik](https://user-images.githubusercontent.com/18627623/177127978-42866d2b-9858-4298-9837-831ec88b1697.png)
Translation: There is not enough storage space available

And here is the configuration I used:
![grafik](https://user-images.githubusercontent.com/18627623/177128543-95738a3f-daab-4c42-a6a8-312bf315d23c.png)

- Windows 11 Pro
- i7-4790K
- Also tested on two seperate drives (both NTFS)

I don't know what else I can provide. Let me know what you need.

**Comment by Yutaka-Sawada** [comment]
While PAR2 supports many source files, it may be less efficient at varied sizes. From watching the sample screen shot, file size differs too much. There are 4 big files (1.0 ~ 2.7 GB) and 5000 small files (154 MB). The efficiency is very low (0.1%).

Instead of creating one PAR2 set for the whole files, you would better create two independent PAR2 sets for group of 4 big files and group of 5000 small files. If a big file may loss, you need to set large redundancy for the big PAR2 set. For example, 10% of 5000 small files are 500 files. So, you will be able to recover 500 small files by using small PAR2 set of 10% redundancy. To recovery 1 big file, you require at least 25% redundancy of 4 big files. As file size are different, you may need more redundancy. You should refer numbers on "Number of files that can be fully reconstructed if missing (Min - Max)".

**Comment by XenonR** [comment]
Ok, I see your point. But my interest is more in covering for bit-rot and similar. There is not too much worry about losing whole files. So what is your verdict? Do I still misunderstand how the size is calculated or is it a bug?
Feel free to close it on your own opinion.

**Comment by Yutaka-Sawada** [comment]
> So what is your verdict? Do I still misunderstand how the size is calculated or is it a bug?

Your posted results were not a bug. The calculation was correct. Because you set large block size, efficiency became very low. Redundancy is set by number of source blocks.

I explain how is the calculation in your example case. When you set 10% redundancy for 5000 source blocks, 500 recovery blocks will be made. Block size is around 1.8 GB in your case. 1.8 GB * 500 blocks = 900 GB. Then, size of PAR2 files will become 900 GB over.

You should set smaller block size. (Set more block count.) By moving "Block Count" slider to right, you may see different result. You see how many blocks in a source file on file-list. It's good to have at least several blocks in the smallest file.

If the block size is 10 MB, block count may become 7000. When 10% redundancy makes 700 reocvery blocks, the size of PAR2 files will be 10 MB * 700 blocks = 7 GB. If the block size is 5 MB, block count may become 8000. When 10% redundancy makes 800 reocvery blocks, the size of PAR2 files will be 5 MB * 800 blocks = 4 GB. If the block size is 2 MB, block count may become 10000. When 10% redundancy makes 1000 reocvery blocks, the size of PAR2 files will be 2 MB * 1000 blocks = 2 GB.

As you set smaller block size, efficiency will become better. But, it will require more time to calculate. The maximum block count is 32768. I don't your PC's speed and how long you can wait. You would better try what setting is good in your case by yourself.

**Comment by XenonR** [comment]
Thanks for explaining in such detail. I understand now the balance between efficency and calculation time as well as how the redundancy works. I very much appreciate the time you took and your work. Thanks a lot 🙂
