### ISSUE TITLE
Add file status sorting function

### ISSUE THREAD

**Issue by K2M74** [Yutaka-Sawada/MultiPar#71]
![image](https://user-images.githubusercontent.com/50667472/182079845-b530862e-730a-4075-b7c8-dbd74a94b4f2.png)
This is useful for quickly finding problem files in a large number of files.

**Comment by Yutaka-Sawada** [comment]
I changed the behavior of `Sort` setting on `MultiPar.ini`. You may edit .INI file to enable sorting by Status.
```
Sort=8
```

I put the sample (gui_sample_2022-08-01.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4?e=UUj7bE). I didn't test so much. Please test by yourself.

**Comment by Yutaka-Sawada** [comment]
I changed a little not to sort by "Number of Blocks" on Create window. It's because, sorting by "File size" and "Number of Blocks" were mostly same. On file-list of Verify window, 3 sorting are possible: Filename, File size, and Status. On file-list of Create window, 2 sorting are possible: Filename and File size. If a user click item header of "Blocks" on Create window, it will disable sorting.

I put the updated sample (gui_sample_2022-08-02.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOg0cF2UHcs709Icv4?e=UUj7bE). When there is a problem or bug, I will fix later. If many users like this feature of "Sorting by Status", I may change the default behavior in future.
