### ISSUE TITLE
windows arm

### ISSUE THREAD

**Issue by thezoggy** [Yutaka-Sawada/MultiPar#73]
Curious if you have look at all into windows arm64 support (native / Arm64EC)?

**Comment by Yutaka-Sawada** [comment]
Currently, MultiPar supports x86 and x64. x86 is 32-bit application. x64 is 64-bit application.
MultiPar.exe : x86
par2j.exe    : x86
par2j64.exe  : x64

It's possible to make ARM and ARM64 applications by Visual Studio 2017 or later. Because I use Visual Studio 2019, my source code will be compatible for ARM or ARM64. From Microsoft's web-page: [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160), compiler switch `_WIN64` targets both x64 and ARM64. But, I cannot test the behavior, as I don't use such ARM machine.

I publiced source code of my PAR2 client; par2j. You may re-compile it for ARM or ARM64 by yourself.

**Comment by coricarson** [comment]
+1 for publishing a Windows arm64 build alongside your regular releases. I have one of these and can test for you.

**Comment by Yutaka-Sawada** [comment]
Thank you for the offer of help. But, it seems to be impossible for me.

[Miscrosoft's documents](https://learn.microsoft.com/en-us/cpp/cpp/m128i?view=msvc-170) says that;
> The __m128i data type is not supported on ARM processors.

Because my par2j uses SSE2 and higher, such SIMD code requires rewrite. SIMD for ARM is called as NEON. Though Visual Studio supports [ARM intrinsics](https://learn.microsoft.com/en-us/cpp/intrinsics/arm-intrinsics?view=msvc-170), I'm difficult to write code by using them. Those who have ARM PC would be able to try.

**Comment by talynone** [comment]
This may help if anyone wants to take it on:

https://developer.arm.com/documentation/102581/0200/Port-with-SSE2Neon-and-SIMDe
