### ISSUE TITLE
par2j64.exe original filename par2j.exe

### ISSUE THREAD

**Issue by thezoggy** [Yutaka-Sawada/MultiPar#76]
jusy fyi:

par2j64.exe original filename par2j.exe
![multipar](http://zoggy.net/explorer_2022-10-05_05-46-05.png)

not sure if scanners will flag that the original file name has been changed, but just to note if there was a tweak in the build where you add the verification after the final filename is created

**Comment by Yutaka-Sawada** [comment]
The `original filename` item is written on a resource script file. It's `res_par2j.rc` in par2j's source code package.

> VALUE "OriginalFilename", "par2j.exe"

Because both 32-bit and 64-bit applications share the same resource, their original filename were same after compile. To distinguish them, I renamed 64-bit version par2j.exe to par2j64.exe manually. When 32-bit OS will be obsolate and I don't need to support 32-bit application, I will release 64-bit version only in future. I don't know how many users still use 32-bit OS. If most users use 64-bit OS, I may change the renaming target. For example, par2j32.exe for 32-bit version and stable for 64-bit version.

Though it's not a bug, there may be confusion in the version info. I will remove the item in the resource script at next version. (It's good time to compile them by Visual Studio 2022.) Then, `original filename` item won't be shown.

**Comment by thezoggy** [comment]
We still distribute multi-par for 32+64 ourselves, I was just reviewing the files as we were updating the included version and I noticed the change and figured I'd call it out in case it shows up as a concern for someone. I do agree that in the 64bit only future it wont matter :)
