### ISSUE TITLE
checksum mismatch, recovery slice 204

### ISSUE THREAD

**Issue by SHA10240** [Yutaka-Sawada/MultiPar#79]
On relative old hardware:
Intel I5-2400
[MultiPar.1.log](https://github.com/Yutaka-Sawada/MultiPar/files/10389885/MultiPar.1.log)

**Comment by Yutaka-Sawada** [comment]
Thank you for reporting the incident. The "checksum mismatch" message indicates memory error on the PC. Even after I updated my compiler, the error seemed to happen rarely on old PCs. Normally, such PCs are very old age or use a specific type of memory module. I think that this was caused by a hardware problem. It's known as "[Row hammer](https://en.wikipedia.org/wiki/Row_hammer)". You may see more articles on the Internet.

It happens on DDR3 or DDR4 SDRAM. Your PC uses them. MultiPar (par2j) processes frequent memory access in a very small area. Then, you may hit the "Row hammer" state rarely.

Because it's a hardware problem, there would be no stable solution. It's good to avoid busy memory access. You may try slower setting on MultiPar Options. Set "CPU usage" slider to lower. Uncheck some "Extra feature". They may mitigate the problem. But, I'm not sure what is good for your case.

**Comment by SHA10240** [comment]
Dear sir,

Thank you for your quick respond.
You are correct:

[image: image.png]

Kind regards,



Nico Somers



Op wo 11 jan. 2023 om 09:40 schreef Yutaka Sawada ***@***.***
