### ISSUE TITLE
MultiPar.exe is considered a Malicious Trojan Malware by VirusTotal

### ISSUE THREAD

**Issue by RobyReal12** [Yutaka-Sawada/MultiPar#85]
MultiPar.exe is considered a Malicious Trojan.Malware by VirusTotal.
Here you can see the result of the scan made by VirusTota: https://www.virustotal.com/gui/file/fb139721582abd8dac3af8c2cc89259401a7556107b975a36a73b84e24bb2bac/detection

It seems that Cynet thinks that MultiPar is a Trojan.Malware.300983.susgen

Just a false positive I suppose but I hope that you can fix this so that people feel safer in using your software.

**Comment by RobyReal12** [comment]
The same thing happens with the .zip version of the software.
Here you can see the result of the scan made by VirusTotal: https://www.virustotal.com/gui/file/340092bf7ec5ba07609d4f8cea66b2a58652b703a396c1b01c1f1a189906831a

McAfee says it is a virus called "Artemis" and Gridinsoft (no cloud) says it is a Trojan.Malware.199584295.susgen

**Comment by Yutaka-Sawada** [comment]
Sometimes a user reports this kind of virus scan result. Basicaly I cannot do anything, because I don't know what is wrong. I cannot fix it, when I don't know where is bad. If someone has a good idea, please write it here.

**Comment by Yutaka-Sawada** [comment]
I feel that some security vendors are almost useless or just stupid. For example, I tested a .EXE file (par1j.exe) in my MultiPar package. This is the [result of v1.3.2.6 par1j.exe](https://www.virustotal.com/gui/file/b537f7765c74f1ed8da341144d9ed358522d1507f3553fd5ce59768d62ba628f/detection). 9 security vendors suspect it. Because some of their analysis are same, they may use same detection engine. From thinking the behavor tag `idle` and `checks-user-input`, creating recovery data might be slow. And it checked a user's cancel key while the heavy task. Because creation or repair requires long time, the behavior may looks something CPU consuming bad action.

Then, I re-compiled par1j.exe by incrementing version number to 1.3.2.8. This is the [result of updated version number](https://www.virustotal.com/gui/file/5d6ed7dba4d66bc44b8330057280cc1c19b16dbd0e03ed55945388aefecfa381/detection). Now, only 1 security vendor suspects it. SecureAge seems to mark Malicious to new .EXE file always. (It may mean that it's not tested so much.) If there is a problem in the .EXE file's behavior or feature, it should be detected as malware everytime. Or, the result will be changed later, when it's used widely. Anyway re-compile .EXE files everytime by the latest Visual Studio may reduce false positive. I will do so at next version release.

**Comment by TeWu** [comment]
Hello, I have a similar question/request, so let me just add to this Issue.

I've checked `MultiPar.exe` (version [v1.3.2.7 beta](https://github.com/Yutaka-Sawada/MultiPar/releases/download/v1.3.2.7/MultiPar1327.zip)) in Hybrid Analysis - here is the report:
http://www.hybrid-analysis.com/sample/df9235edd689e78e0a37f244a5ea9727a01b3833a7a7fd5693cb22fe28d6dd7a/63fe8c6bb61e1138530e0644
The executable has been classified as "malicious". There are some details, so you can see why it was classified like that. In general I would suggest making changes to improve the scanning result.

Personally I'm curious about the `"MultiPar.exe" called "OpenServiceW" to access the "mpssvc" service ("Windows Firewall")`. Why `MultiPar.exe` calls to the Windows Firewall Service?
I tried to investigate, and I can see the source for `par1j.exe`, `par2j.exe` and `sfv_md5.exe` ([here](1)) but I can't seem to find the source for `MultiPar.exe`. What am I missing?

[1]: https://github.com/Yutaka-Sawada/MultiPar/tree/master/source

**Comment by Yutaka-Sawada** [comment]
I read the `Risk Assessment`. Because MultiPar is a front-end (launcher) of other .EXE files, basically the behavior is risky. It's interesting that what behavior is thought to be `Malicious Indicators`. 

1) `Tries to hide tracks of having downloaded a file from the internet`
Erasing "Zone.Identifier" is thought as `Anti-Detection/Stealthyness`. I added the feature, because the blocking is annoying.

2) `References security related windows services` and `Requested access to a critical system service`
These are source of your question.

> Why MultiPar.exe calls to the Windows Firewall Service?

I don't know, because I don't use it. If it calls OpenService, it's a strange behavior. I'm not sure how MultiPar.exe calls it.

> but I can't seem to find the source for MultiPar.exe. What am I missing?

MultiPar GUI (MultiPar.exe) is closed source as same as QuickPar.

**Comment by Yutaka-Sawada** [comment]
3) `Spawns a lot of processes`
The `WerFault.exe` seems to be Error Reporting tool of Microsoft. Something error might occur while test.


#### Changes for next version.

I will remove the auto erasing "Zone.Identifier" feature from MultiPar.exe. A user would erase the flag manually.

I found that Windows 10 didn't have `Protected Storage System Provider` key in registory. I will remove checking user name for batch processing. Though I set the feature to distinguish users, most users won't share MultiPar with same setting.

**Comment by Yutaka-Sawada** [comment]
While I read [a sandbox reports on VirusTotal](https://www.virustotal.com/gui/file/df9235edd689e78e0a37f244a5ea9727a01b3833a7a7fd5693cb22fe28d6dd7a/behavior), I found a network traffic. The address seems to be Microsoft over akamaitechnologies.com. I think that `Microsoft.Windows.Common-Controls` or `Microsoft Visual C++ Runtime Library` may try to access network. Or `WerFault.exe` may try to report an error to Microsoft.

From [the report of Falcon Sandbox](https://www.hybrid-analysis.com/sample/df9235edd689e78e0a37f244a5ea9727a01b3833a7a7fd5693cb22fe28d6dd7a/63fe8c6bb61e1138530e0644), a string `mpssvc` indicates access to Windows Firewall. But, I could not find the string in MultiPar.exe. I don't know where the sandbox find it.

**Comment by KwietekMiki** [comment]
> This is the [result of v1.3.2.6 par1j.exe]
(https://www.virustotal.com/gui/file/b537f7765c74f1ed8da341144d9ed358522d1507f3553fd5ce59768d62ba628f/detection). **9 security vendors suspect it.**

![image](https://user-images.githubusercontent.com/125089837/230656262-bd402c35-cf75-4011-acd8-6e05488b6d2d.png)
