### ISSUE TITLE
2 features that can be very important , please guys vote for this

### ISSUE THREAD

**Issue by DEVUVO** [Yutaka-Sawada/MultiPar#9]
Hello there , i would like to see 2 options in multipar please

1 - run in background option , as if i am verifying some files or and more than one .par2  

so if i have 2 rar files and there is 2 sets of par one  set for each rar 

i need to run the par2 files in the background without keep popping on my screen as i am doing other work , just imagine dealing with 10k plus i have to keep closing the windows while i am doing my work , specially where there is a missing rars , or blocks or not able to repair , so the auto option is not very useful this way

2 - an option to remove the par files if there is no missing blocks or files  and the file set is 100 % complete , 

same as above if dealing with tons of par2 files there is no reason to delete par files for every set of files if there is no need for the par files anymore 

Thank you and please if you accept donation let us know how . thanks.

**Comment by Yutaka-Sawada** [comment]
> 1 - run in background option

I'm not sure what it does. You can minimize MultiPar window, while verification.

> 2 - an option to remove the par files

This may be risky as an automated action. You can use Batch Script to verify and delete PAR files.

Or, you may use MultiPar's feature to start batch file. I put a sample batch script here.
Make a file "auto_v.cmd" in save folder of MultiPar, and write following code.
```
@ECHO OFF
TITLE Delete PAR files
SETLOCAL

REM Verification result = %3
REM 0   = complete
REM 256 = PAR files are incomplete
SET /A "verify_result = %3 & 255"

REM Construct PAR file names
SET index_path=%1
SET other_path="%~dp1%~n1.vol*+*.par2"

IF %verify_result% EQU 0 (

ECHO index path = %index_path%
ECHO other path = %other_path%
DEL %index_path%
DEL %other_path%

)

PAUSE
```

You check "Start batch script" on MultiPar option. 
When you open an index file (such like something.par2) with MultiPar, successful verification will delete the file and other files (such like something.vol0+10.par2). Be careful. Deleted PAR files don't move to Recycle Bin.
If you don't want to see process result, omit the last line 's "PAUSE".

**Comment by JohnLGalt** [comment]
> 
> 
> > 1 - run in background option
> 
> I'm not sure what it does. You can minimize MultiPar window, while verification.

Technically, what he meant was the ability to run with lower process priority, allowing for better multi-tasking, versus actually runnning in the bg (which is more of a concept for running apps without a UI or launched via Windows  services).  However, many apps simply call it run in background mode when they really mean run with a lower priority.  If you open Task Manager you can usually (with newer versions anyway) see a process and right click on it and see the ability to set both affinity (# processors) as well as Priority (I believe this is thread scheduling, but it might be referred to by a different name, since I am not the programmer here I'm only relating the info as I know it).
> 
> > 2 - an option to remove the par files
> 
> This may be risky as an automated action. You can use Batch Script to verify and delete PAR files.
> 
> Or, you may use MultiPar's feature to start batch file. I put a sample batch script here.
> Make a file "auto_v.cmd" in save folder of MultiPar, and write following code.
> 
> ```
> @ECHO OFF
> TITLE Delete PAR files
> SETLOCAL
> 
> REM Verification result = %3
> REM 0   = complete
> REM 256 = PAR files are incomplete
> SET /A "verify_result = %3 & 255"
> 
> REM Construct PAR file names
> SET index_path=%1
> SET other_path="%~dp1%~n1.vol*+*.par2"
> 
> IF %verify_result% EQU 0 (
> 
> ECHO index path = %index_path%
> ECHO other path = %other_path%
> DEL %index_path%
> DEL %other_path%
> 
> )
> 
> PAUSE
> ```
> 
> You check "Start batch script" on MultiPar option.
> When you open an index file (such like something.par2) with MultiPar, successful verification will delete the file and other files (such like something.vol0+10.par2). Be careful. Deleted PAR files don't move to Recycle Bin.
> If you don't want to see process result, omit the last line 's "PAUSE".

Oh, that is bloody brilliant!  Thank you for sharing!

**Comment by Yutaka-Sawada** [comment]
I write a sample batch script to verify and open MultiPar (when bad state) or delete PAR files (when complete). This sample includes a switch by ERRORLEVEL. You may customize these code for your special task.

Make a file "VerifyAnd.cmd", and write following code. Specify path of 3 items. The path should be cover by "", such like "C:\somewhere\MultiPar\par2j64.exe" or "C:\somewhere\MultiPar\save". It's good for when there is space in file or folder name. 
You can check MultiPar's folder and MultiPar's save folder at Option window. There is a "Folder location" section on "System settings" tab.

```
@ECHO OFF
SETLOCAL

REM Input path must be "something.par2".
IF /i "%~x1" NEQ ".par2" GOTO End

SET par2_path="path of par2j64.exe"
SET multipar_path="path of MultiPar.exe"
SET save_dir="directory of save folder"

REM Verify and save result
%par2_path% v /vs1 /vd%save_dir% "%1"

ECHO ERRORLEVEL = %errorlevel%
IF NOT ERRORLEVEL 1 GOTO ResultOK
IF ERRORLEVEL 256 GOTO ResultOK

REM Process following code, when something bad in source files.

ECHO Open MultiPar to see details of bad state.
START "" %multipar_path% /verify "%1"
GOTO End

:ResultOK
REM Process following code, when source files are complete.

ECHO Deleting PAR files, as source files are complete.
SET other_path="%~dp1%~n1.vol*+*.par2"
DEL "%1"
DEL %other_path%

:End
ENDLOCAL

PAUSE
```

In MultiPar option, you must set "Re-use verification result" to be some days. MultiPar can share verification result. If "Not used" is selected, MultiPar needs to re-start verification. 

When you Drag & Drop an index file (such like something.par2) on the batch file, successful verification will delete PAR file and other files (such like something.vol0+10.par2). If there is something bad state, it will open MultiPar to show the details. 

Be careful. Deleted PAR files don't move to Recycle Bin. 
If you don't want to see process result, omit the last line 's "PAUSE".

**Comment by Yutaka-Sawada** [comment]
> what he meant was the ability to run with lower process priority,

There is an option "Run clients with lower priority" on MultiPar. Now, it decrease PAR client's priority to be one level. I will decrease MultiPar GUI's priority also at next version. (PAR client will be two level lower.) On Multi-Core CPU, there seems to be no big difference mostly. Even when MultiPar GUI is foreground, the priority may become same as background application by this change.

**Comment by DEVUVO** [comment]
Hello  , thank you for the reply and trying to help , well this is my case i will try to say more details

1 - run in background option 

If i have 10k folders each folder contains rar parts , each folder has its own par set ,

i have a tool called everything search that i can choose 100 par file or more to verify that all my backups are not missing

when i run the multipar it keep showing me 100 windows one after another , so even if there is no missing blocks it will keep pop up one after another  untill its auto closed , and the missing blocks windows will remain in the taskbar ,

is there is anyway to keep the multipar run hidden into the tray without showing in taskbar , very annoying , now i dont low cpu usage , i set mine to max i got a powerful server that do the job but it keep pop up windows , i can't just keep click no and minimize for each windows while doing other office work ,



2 - an option to remove the par files

```
@ECHO OFF
TITLE Delete PAR files
SETLOCAL

REM Verification result = %3
REM 0   = complete
REM 256 = PAR files are incomplete
SET /A "verify_result = %3 & 255"

REM Construct PAR file names
SET index_path=%1
SET other_path="%~dp1%~n1.vol*+*.par2"

IF %verify_result% EQU 0 (

ECHO index path = %index_path%
ECHO other path = %other_path%
DEL %index_path%
DEL %other_path%

)

PAUSE
```


I don't know how to use a script ? im not a programmer  , is there is an option please that you can add to choose in the next version , so we can tick or not if we need the feature ,

i tried many software to hide the multipar in tray but each par2 file i am verifying has its own  window i cant keep add 100 or 500 par2 file each time i am running the multi par





Now here comes another question  , if there is away to make a window inside the multi par and will verify multi par2 files in a single windows

like multihash software , or any other program drag drop verify without opening a window for each par2 file 


thank you so much .

**Comment by Yutaka-Sawada** [comment]
> when i run the multipar it keep showing me 100 windows one after another , so even if there is no missing blocks it will keep pop up one after another untill its auto closed , and the missing blocks windows will remain in the taskbar

I see your case.

> is there is anyway to keep the multipar run hidden into the tray without showing in taskbar

Task Tray is good for a few resident programs to indicate their status. It's not good for user's temporary applications. If there are many icons in your task tray, it's hard to see them.

I think that setting the Verify window to be minimize state at the start may be good. MultiPar's Verify window will go to task-bar directory without clicking minimize button. When you check "Close automatically" option, the task-bar button for complete set will disappear after verification. After finish verification of 100 PAR2 sets, there will be only some task-bar buttons for bad state set. 

I made a sample to test the behavior. I put the sample (gui_sample_2020-09-14.zip) in "MultiPar_sample" folder on [OneDrive](https://1drv.ms/u/s!AtGhNMUyvbWOaSo1n_R8awJ_hg0?e=4V0gXu). Please test it in your usage.

Because I didn't modify GUI yet, you need to add a line on "MultiPar.ini" manually. The setting file "MultiPar.ini" exists in MultiPar's install folder or user's folder. Add a line of "VerifyWindow=1" under "[Option]" section in "MultiPar.ini". 
It's like below;
```
[Option]
VerifyWindow=1
```

**Comment by DEVUVO** [comment]
I did it and the windows seems to run in the background but there is something weird just happeend , 

The my computer just run by itself during or after the process , i can wait till the next version no hurry this should be enough for now , thank you so very much ,

**Comment by JohnLGalt** [comment]
@Yutaka-Sawada Lower priority + background would work well for DEVUVO, but is there also a way to, perhaps, process the par files *sequentially* versus simultaneously?  I think batch can possibly help with that too....

**Comment by Yutaka-Sawada** [comment]
> but is there also a way to, perhaps, process the par files sequentially versus simultaneously?

I'm not sure what you want.
When a user opens some PAR files at once, the difference may be like below;
sequentially = some MultiPar instances will verify each PAR set one by one.
simultaneously = some MultiPar instances will verify all PAR sets in same time.

By default, MultiPar verifies one by one sequentially. (Other instances become waiting state.) 
Only when "Don't wait finish of other tasks" option is checked, they verify every PAR set in same time. (This cause HDD busy and may become slow.)

**Comment by JohnLGalt** [comment]
I think that that feature is not working as intended.  Below, I attempt to recreate what DEVUVO is doing, using different apps, but still getting the same results as he is.

First, verification that that setting is disabled in MP:

![MP 001](https://user-images.githubusercontent.com/7432512/93621050-006aa600-f9a9-11ea-8527-dfab1ece414d.png)

Second, manual search for .par2 files:

![MP 002](https://user-images.githubusercontent.com/7432512/93621077-0f515880-f9a9-11ea-81c4-7ab6ec72ec55.png)

Third, showing that I open the files directly in MP:

![MP 003](https://user-images.githubusercontent.com/7432512/93621106-1aa48400-f9a9-11ea-83c3-2879a987720f.png)

Finally, showing that MP still opens multiple instances of itself to process those files, rather than sequentially processing them in the same window one at a time:

![MP 004](https://user-images.githubusercontent.com/7432512/93621205-390a7f80-f9a9-11ea-906b-345096c58b8c.png)

Now I realize that processing one at a time would be a massive overhaul of the application, as you would need to code in what to do if errors are found, how to pause the processing of files so said errors could be dealt with without losing the rest of the files waiting to be processed in the queue, and such - but nonetheless, when doing multiple files simultaneously, multiple instances of MP get opened, and if that other setting show, running at lower priority, is not enabled, then it can easily cause your system to slow down / lock up.

I realize that this is a niche case - most people are *NOT* going to try to run multiple files simultaneously.  And I also realize that handling multiple files simultaneously is probably best done in a batch environment.  However, currently, processing files in this manner does cause some serious system stress as the instances are loaded up into memory, before actual processing begins.

In fairness, it does seem that each set is processed individually, so the processing itself is not running simultaneously - just as the setting indicates.  However, initially, when starting up with multiple files selected, all the instances open immediately, and then there is a ... lag, for lack fo a better word, as each instance does whatever it is doing in the pre-processing phase, and that seems to be running simultaneously (i.e. with concurrent threads).

I hope this helps explain what DEVUVO was referring to.

**Comment by DEVUVO** [comment]
@ JohnLGalt  . yes that explains much better  , my windows are showing different in a group of icons over each other thats how i group multi windows from same apps to open in a one group under multi stacked icons ,

however cpu i use max cpu usage it dont matter to me what i am worry about is i wish all the process to run from one window 

if you see the RekSFV app when you drop multi sfv files it will just process one after another , it will not run multi sfv at the same time , 

in this case we can just stop worry about over usage of CPU for some people and also nice small quick ways and keep the options as its also one windows drag drop will save so many option from the current feature , such as , dont wait to finish other par2 files 

once the par2 done its will logged in a log file if any failed , using a txt file or any doc file to go over it later if saved , option to copy the logs from the windows or save as txt or other file types 

i think it worth the wait the current method i used above still good but still running like 600 par2 at one time is insane dealing with 100k plus takes time , even so i have to do it over and over i tried 700 par2 at one time the app freezes and the apps will not till i force kill it from TASKMANGER

hope this brings the topic back to life waiting for Yutaka if he think he would work this out then that would be great , if not then i will close this topic ,

**Comment by JohnLGalt** [comment]
> 
> 
> @ JohnLGalt . yes that explains much better , my windows are showing different in a group of icons over each other thats how i group multi windows from same apps to open in a one group under multi stacked icons ,
> 
> however cpu i use max cpu usage it dont matter to me what i am worry about is i wish all the process to run from one window
> 
> if you see the RekSFV app when you drop multi sfv files it will just process one after another , it will not run multi sfv at the same time ,
> 
> in this case we can just stop worry about over usage of CPU for some people and also nice small quick ways and keep the options as its also one windows drag drop will save so many option from the current feature , such as , dont wait to finish other par2 files
> 
> once the par2 done its will logged in a log file if any failed , using a txt file or any doc file to go over it later if saved , option to copy the logs from the windows or save as txt or other file types
> 
> i think it worth the wait the current method i used above still good but still running like 600 par2 at one time is insane dealing with 100k plus takes time , even so i have to do it over and over i tried 700 par2 at one time the app freezes and the apps will not till i force kill it from TASKMANGER
> 
> hope this brings the topic back to life waiting for Yutaka if he think he would work this out then that would be great , if not then i will close this topic ,

Mine also show as stacked windows after I reach a threshold, but if you hover the mouse over the stacked icons, it splits them open as in my screen shot.

As for CPU usage - lol I just built a new machine with Ryzen 9 3950X and 128 GB of 3600 MHz DDR4 (yes, not a typo - I really have 128 GB RAM) - so I'm obviously not *too* worried about either CPU or RAM usage - but when processing multiple files simultaneously, after about 10 I see a noticeable decrease in system usability, and hte time frame for that decreased usability scales with number of files I try to open at one time.

As for Yutaka getting back to us - do remember that he has stated more than once that his development machine is not new, and thus is limited in what he can bring to the table.

TBH, I'd love it the GUI were to be fully OS so we could use a different CLI with it, like the one you linked to that supports much better, newer instruction sets.  With the RAM I have I should have no problem doing several hundred verification attempts at one time, but if the GUI were to process them sequentially, it would make things a lot better, for sure.  Your idea for error output is a good one, but that would *definitely* require additional coding (perhaps even an overhaul) of MP as it sits now.

**Comment by DEVUVO** [comment]
Maybe if someone with some coding experience can get with yutaka and do some virtual machine or even direct remote to build up and test some new gui , this is going to make the app waaaaaaaaay much better , drag drop multi par2 files and forget it and at the end just have a fail log window , or a generated log file , omg that would be magic . :)
