### ISSUE TITLE
checksum mismatch, recovery slice 

### ISSUE THREAD

**Issue by CMTriX** [Yutaka-Sawada/MultiPar#90]
Windows 11 22h2 (all updates installed)
memory check: no ram defaults detected.
i5-11600K

I am getting this error al the time. Windows is working fine, no errors in other programs. 
I found topics here, made changes to the settings of multipar. Nothing helps.

what is wrong?

`8-7-2023 13:00:57
par2j64.exe c /uo /ss3441484 /rn210 /vs1 /vdsave /rf1 H:\testfilepar.par2 testfilepar.part01.rar testfilepar.part02.rar testfilepar.part03.rar testfilepar.part04.rar testfilepar.part05.rar testfilepar.part06.rar testfilepar.part07.rar testfilepar.part08.rar testfilepar.part09.rar testfilepar.part10.rar
Parchive 2.0 client version 1.3.2.8 by Yutaka Sawada

Base Directory	: "H:\"
Recovery File	: "H:\testfilepar.par2"
CPU thread	: 6 / 12
CPU cache limit : 64 KB, 768 KB
CPU extra	: x64 SSSE3 CLMUL AVX2
Memory usage	: Auto (56091 MB available), Fast SSD

Input File count	: 10
Input File total size	: 10312392900
Input File Slice size	: 3441484
Input File Slice count	: 2997
Recovery Slice count	: 210
Redundancy rate		: 7.00%
Recovery File count	: 1
Slice distribution	: 0, uniform (until 210)
Packet Repetition limit	: 0

  0.0% : Computing file hash
 17.6%
 40.1%
 57.9%
 80.2%
 93.6%
100.0%
  0.0% : Making index file
100.0%
  0.0% : Constructing recovery file
100.0%
  0.0% : Creating recovery slice
  0.7%
  1.5%
  2.3%
  3.1%
  3.8%
  4.6%
  5.3%
  6.0%
  9.1%
 12.1%
 14.7%
 17.3%
 20.3%
 23.3%
 26.4%
 28.9%
 31.5%
 34.1%
 37.1%
 40.1%
 42.7%
 45.7%
 48.7%
 51.3%
 53.9%
 56.9%
 59.5%
 62.5%
 65.5%
 68.1%
 70.3%
 72.8%
 75.4%
 78.0%
 80.6%
 83.2%
 85.7%
 88.3%
 90.9%
 93.9%
 96.5%
 99.7%
checksum mismatch, recovery slice 196`

**Comment by CMTriX** [comment]
Update: when i turn of the Windows Defender it completes the job.. Going to test more.

**Comment by Yutaka-Sawada** [comment]
The "checksum mismatch" message indicates error of DRAM. It's rare, and it depends on PC usage. It's known as "[Row hammer](https://en.wikipedia.org/wiki/Row_hammer)". You may check the problem by special test of memtest86. Normal memory test of Windows OS cannot detect the failure, because it happens at very frequent memory access in small area.

The problem happened mostly on old PC with DDR2 or DDR3 memory. But, [it seems to happen on DDR4 memory](https://www.vusec.net/projects/trrespass/), too. Because it's a hardware problem, it's difficult to solve by software side. Slower memory access is a solution, but it causes slower encoder. While most users don't see the error, I don't want to decrease speed of encoder.

If you can change memory setting on BIOS of your PC, try slower memory access rate. You may try slower setting on MultiPar, too. There are "Hardware environment" section on "System settings" tab. "CPU usage" to lower (left side). Disable "AVX2" or "SSSE3". Smaller "Memory usage". I cannot say what is good for your PC.

Only when you cannot solve problem by settings, I may make a debug version to test slower encoder. But, I could not find good way in previous similar cases.

**Comment by CMTriX** [comment]
Issue is solved.
Did 1 night a memtest no error.

I did recently updated the firmware of the motherboard. before the update Multipar worked fine.
After the firmware update it failed always.

i loaded the bios with default settings, and changed my settings back.

All par jobs are now completed without errors.. 

Thanks for your input! (and tool!)

**Comment by Yutaka-Sawada** [comment]
Oh, I see. It's a good news that problem was solved. Because recent large size DRAM module is dense and may weaken against noise, memory access timing might be bad somewhere. I will close this issue later.
