### ISSUE TITLE
feature request for par2j/par2j64

### ISSUE THREAD

**Issue by Killua-Zolldyck** [Yutaka-Sawada/MultiPar#91]
Hi,

I wonder, if it is possible to add a switch, to reduce the verbosity to only show progress status and error messages.

Thank you for reading. 😊

Kind Regards

**Comment by Yutaka-Sawada** [comment]
Technically, it's easy to reduce output. It just needs a switch for "Quiet mode" or "Silent mode". I have implemented the mechanism in par3cmdline. Though I don't use PC at hot summer so much, I will try how to do in par2j.

"Quiet mode" (less output) 's problem is what to show (and hide). What you means "progress status" ? "Silent mode" (disable all output) will be easier, because it doesn't need to decide. As "Quiet mode" will skip most output text, it may show meaningless numbers for sign of running.

Do you need conclusion of process at the last ? It's such like; "Created successfully" at creation, "All Files Complete" at Verification, or "Repaired successfully" at repair. I don't know what is your usage. Do you check "Exit code" to know result instead of reading text ?

**Comment by Killua-Zolldyck** [comment]
Hi again,

Thank you for your message.

I'm using the CLI only for creating PAR Files in automated scripts. For there are some more commands in my scripts, I've reduced the output to the messages, that are really important or just showing the state, what is done at the moment. So ffmpeg is just returning the processing status and errors until finished. Rar is showing errors only for their silent mode has no option to show the progress. So it would be fine for me, if the output auf par2j would be silent except errors. If you implement a "quiet mode" which then will only show errors and the states "Computing file hash", "Making index file", "Constructing recovery file", "Creating recovery slice", as it is now, when creating a par2, I would love to use this.

> Do you check "Exit code" to know result instead of reading text ?

Not yet. At the moment it is just for private use and would just help me to reduce the text I have to read, when I run my scripts. So it isn't that important and I can undestand, if you put this at the end of your to-do list.

Kind Regards

**Comment by Yutaka-Sawada** [comment]
> I'm using the CLI only for creating PAR Files in automated scripts.

Oh, I see. I thought that it might be verification/repair usage. When you create PAR2 files at scripting, you would better use ParPar tools instead of my par2j. They are [ParPar for NodeJS](https://github.com/animetosho/ParPar) or [speed focused par2cmdline](https://github.com/animetosho/par2cmdline-turbo). The par2cmdline has switch to reduce output.

I tested the speed of them. There are 4 source files of 3.13 GB. I made PAR2 files of 10% redundancy with 512 KB block size (6417 blocks). Because my PC has 16 GB RAM, all files are cached on RAM. CPU is Intel Core i5-10400.

original par2cmdline : 3 min 5 sec
par2cmdline-turbo : 18 sec
par2j : 28 sec

So, using ParPar (or par2cmdline-turbo) would be faster mostly. par2cmdline-turbo is 10 times faster than original par2cmdline, and 55% faster than my par2j. Only when you have super fast graphics board, my par2j may be faster for big files. But, I'm not sure.

**Comment by Killua-Zolldyck** [comment]
Thanks again for your answer.

I've been so satisfied with MultiPar over the past years, it never came into my mind to look for another tool... So I didn't know these both up to now.

Tested them all on a 46.2GB multi-part rar (190 files) with 5% redundancy, 4MB block size (607 blocks) (i9-13900K, 64GB RAM, RTX3090, nVME 2.0 SSD):
- par2j64 (CPU only): 5m 38s
- par2j64 (CPU+GPU): 2m 46s
- parpar: 4m 18s
- par2cmdline-turbo: 18m 23s....???

I don't know, whats wrong with par2cmdline-turbo in my environment, but I definitively won't use this. Looking at the rest par2j64 with GPU acceleration is by far off the fastest way.

For I disable GPU for PAR2 generation, bc the GPU is used for other things on most of the time, parpar will do the job for me with nice handling of verbosity, too. Thank you for the hint to this. Of course I will continue using MultiPar GUI for non-scripted jobs and repair issues.

Best Regards
