### ISSUE TITLE
Feature Request: Batch Mode

### ISSUE THREAD

**Issue by eddilara** [Yutaka-Sawada/MultiPar#93]
how about a Batch mode where you point it to a folder and it will find all the par files in that folder and under that folder and fix them

**Comment by Yutaka-Sawada** [comment]
MultiPar includes such Python script in `tool` folder. The file name is `queue_verify.py`. The description is "Verify multiple PAR2 sets in a selected folder with Queuing GUI" on "Python script" item (`help\0409\python.htm`) of help documents.

Though it doesn't search children folders by default, you can edit it for recursive search. Though it verifies only now, you can edit it to repair automatically. Because I wrote each case already, it's easy to change the behavior. Anyway, you need to install [Python language](https://en.wikipedia.org/wiki/Python_(programming_language)) on your PC.

**Comment by eddilara** [comment]
would be MUCH better to have a GUI for it

**Comment by Yutaka-Sawada** [comment]
I'm not sure what GUI you think. The Python script shows GUI to see/pause/resume/stop queue. It's hard to make something, when it's unknown.

**Comment by eddilara** [comment]
you open the program....have a button somewhere that says load folder....you pick the folder you want it to check...and it finds all the par2 files there..and then you push start or go to fix/check the files

**Comment by Yutaka-Sawada** [comment]
Yes. My script (`queue_verify.py`) does that action on GUI. You may try it.
