### ISSUE TITLE
 Is this a bug?

### ISSUE THREAD

**Issue by Huandeep** [Yutaka-Sawada/MultiPar#96]
When there's an empty file in there 
![动画](https://github.com/Yutaka-Sawada/MultiPar/assets/30691481/0a77da7a-abec-4288-9886-fcfb5bc7990a)

**Comment by Yutaka-Sawada** [comment]
No, it's not a bug. I'm not sure what is wrong for you. After you renamed your files, it restored all of them correctly.

When a folder's name was changed (it became different folder), it detects the inner file as "Moved status". To repair this case, it recreates missing folders and brings back moved files.

Now, empty file is the problem. It cannot distinguish empty files each other, when the filename was changed. If you didn't rename the empty file, it recognizes it as "Moved status". Because you renamed empty file, it failed to find it. Then, it just recreated the empty file in restored folder.
