### ISSUE TITLE
Virus (?)

### ISSUE THREAD

**Issue by Skyotiago** [Yutaka-Sawada/MultiPar#98]
Multipar setup was identified as virus by Microsoft Edge, VirusTotal and SmartScreen. True?

**Comment by Yutaka-Sawada** [comment]
> True?

I don't know how it works. Because Microsoft Edge said so, you should ask to the developer (Microsoft) by yourself. I feel that Microsoft Edge's SmartScreen seems to show alert for new .EXE file always. When a .EXE file was created recently, its download count is a few times. After many people downloaded the file, Microsoft would consider it as safe.
